### ISSUE TITLE
Use consistent common name

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#10]
Only 11 of the 810 animals have a common name:

- 7 `Atlantic cod` (`2015 PhD Verhelst`)
- 4 `Fint` (`2015 Fint`)

The definition of the field is `The species' common English name`, so `Fint` is incorrect. I would argue to either always populate the common English name or never.

**Comment by peterdesmet** [comment]
Suggestions anyone regarding populating this field?

- Either we do it for all, or not at all. I think it would be useful.
- I would choose the English common name (cf. definition of field)

**Comment by peterdesmet** [comment]
Suggestion:

scientific name | common name | animals | alternatives
--- | --- | --- | ---
Alosa fallax | twaite shad | 44 | twait shad
Anguilla anguilla | European eel | 402 | 
Cyprinus carpio | common carp | 2 | European carp
Gadus morhua | Atlantic cod | 147 | 
Homarus gammarus | European lobster | 2 | common lobster
Lampetra fluviatilis | river lamprey | 39 | European river lamprey, lampern
Petromyzon marinus | sea lamprey | 2 | 
Platichthys flesus | European flounder | 8 | 
Rutilus rutilus | roach | 6 | common roach
Salmo salar | Atlantic salmon | 135 | 
Silurus glanis | wels catfish | 20 | sheatfish
Squalius cephalus | chub | 3 | common chub, European chub

@pieterjanverhelst @jreubens let me know if you agree with the names above (or prefer one of the alternative names to be used)

**Comment by jreubens** [comment]
I agree with the 'marine' species. I leave it to @PieterjanVerhelst to decide for roach and lamprey (those are the only two I'm doubting)

**Comment by PieterjanVerhelst** [comment]
The common names are the correct ones, except for 'European river lamprey' anc 'common chub'. This can be changed to just 'river lamprey' and 'chub' respectively.

**Comment by peterdesmet** [comment]
Updated. @fwaumans please populate `COMMON_NAME` as follows:

scientific name | common name
--- | ---
Alosa fallax |  twaite shad
Anguilla anguilla |  European eel
Cyprinus carpio |  common carp
Gadus morhua |  Atlantic cod
Homarus gammarus |  European lobster
Lampetra fluviatilis |  river lamprey
Petromyzon marinus |  sea lamprey
Platichthys flesus |  European flounder
Rutilus rutilus |  roach
Salmo salar |  Atlantic salmon
Silurus glanis |  wels catfish
Squalius cephalus |  chub

Any existing values for these species can be overwritten.

**Comment by fwaumans** [comment]
The common names are updated by the proposed values.

**Comment by peterdesmet** [comment]
:+1:
