### ISSUE TITLE
Add missing capture and release latitude/longitude

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#11]
**Update: this text and table is an updated with the most recent information, based on the comments in this usse**

It is important that the **capture event** and **release event** have coordinates. This is already the case for 574 animals, but for 236 those coordinates are missing. I understand it might be difficult to retroactively add those coordinates, but maybe it is possible based on the `captureLocation` and `releaseLocation`?

The table below shows how many animals per project have/don't have capture and release coordinates. Where `FALSE` they should be added.

projectName | capture_coordinates | release_coordinates | number of animals
--- | --- | --- | ---
**2013 Albertkanaal** | FALSE | TRUE | 112
**2013 Albertkanaal** | FALSE | FALSE | 29

**Comment by peterdesmet** [comment]
@IPauwels where would we be able to find the capture/release coordinates for fish in 2013 Albertkanaal, 2011 Rivierprik, 2015 Fint.

@jreubens @pieterjanverhelst can you add the missing coordinates for Homarus & 2015 PhD Verhelst?

**Comment by jreubens** [comment]
homarus should be updated

**Comment by PieterjanVerhelst** [comment]
The missing lats and longs are for cods tagged during my PhD. I updated some of them, but I am still missing coordinates.
@jreubens, do you have the coordinates of the following locations:
'SS AURETTA', 'D5 C-Power', 'C05 Belwind', 'Kilmore' and 'Spijkerplaat (thv Stella)'

**Comment by jreubens** [comment]
@PieterjanVerhelst : D5 you can find at animals of my PhD; Kilmore and C05 are also deployment station. Spijkerplaat en SS aurettaa will have to search for on wreck chart and navigation chart respectively

**Comment by PieterjanVerhelst** [comment]
I added some missing coordinates. The only ones that are still missing are:
- `Spijkerplaat` and `SS Auretta` (Jan Reubens will look for these coordinates)
- `C05 Belwind` for the project `Flatfish`, as I do not have writing access to this project. @jreubens, can you complete these three empty records?

**Comment by LienReyserhove** [comment]
This is an updated overview of the projects with lacking coordinates. 
For 2013 Albertkanaal, the number of lacking coordinates have increased. For 2015 PhD Verhelst, the numbers have decreased. I suppose most of the lacking coordinates are to be completed by @IPauwels.

projectName | capture_coordinates | release_coordinates | number of animals | OK
--- | --- | --- | --- |---
2011 Rivierprik| FALSE | FALSE | 39 |
2013 Albertkanaal | FALSE | TRUE | **125** |
2013 Albertkanaal | FALSE | FALSE | 29 |
2015 Fint | FALSE | FALSE | 1 |
2015 PhD Verhelst | FALSE | FALSE | **21** |
Homarus | FALSE | FALSE | 2 | OK

**Comment by jreubens** [comment]
missing coordinated for 'spijkerplaat', 'ss Auretta' and 'C05' have been added.

**Comment by LienReyserhove** [comment]
This is a copy-paste from the https://github.com/inbo/etn-occurrences/issues/41#issuecomment-529480105 by @IPauwels 

> Fishes caught at ‘Hatchery Erezée’ are hatched fish that were given a tag in the Hatchery of Erezée. The coordinates of the hatchery are: lat/long: 50.306056 , 5.542595. So these are the coördinates for both the catch and surgery location of fishes of catch location ‘Hatchery Erezée’.

I integrated this information in the Darwin Core mapping, but this information should also be added to the database!

**Comment by IPauwels** [comment]
I think Fint is completed now? Can you confirm this, please?

**Comment by IPauwels** [comment]
For Albertkanaal: see my comment in the other issue please.
https://github.com/inbo/etn-occurrences/issues/41#issuecomment-531699707

**Comment by LienReyserhove** [comment]
@IPauwels yes, indeed, all coordinates for the FINT data are updated now. Thanks for that!

**Comment by peterdesmet** [comment]
Current situation:

## capture loc coordinates missing

```R
get_animals(animal_project_code = c("2011_rivierprik", "2012_leopoldkanaal", "2013_albertkanaal", "2014_demer", "2015_dijle", "2015_phd_verhelst_eel", "2015_phd_verhelst_cod", "2015_homarus", "2010_phd_reubens", "2010_phd_reubens_sync")) %>%
  mutate(capture_coordinates = if_else(is.na(capture_latitude) | is.na(capture_longitude), FALSE, TRUE)) %>%
  filter(!capture_coordinates) %>%
  group_by(animal_project_code, capture_location, capture_coordinates) %>%
  count() %>%
  View()
```

animal_project_code | capture_location| n
--- | --- | ---
2010_phd_reubens | ~NA~ | 12
2010_phd_reubens_sync | NA | 15
2013_albertkanaal | ~Diepenbeek~ | 2
2013_albertkanaal | ~Genk~ | 7
2013_albertkanaal | ~Hasselt~ | 3
2013_albertkanaal | hatchery Erezée | ~128~ 2: to be corrected later
2013_albertkanaal | ~NA~ | 13
2015_phd_verhelst_cod | ~B05 Belwind~ | 3

## release loc coordinates missing

```R
get_animals(animal_project_code = c("2011_rivierprik", "2012_leopoldkanaal", "2013_albertkanaal", "2014_demer", "2015_dijle", "2015_phd_verhelst_eel", "2015_phd_verhelst_cod", "2015_homarus", "2010_phd_reubens", "2010_phd_reubens_sync")) %>%
  filter(is.na(release_latitude) | is.na(release_longitude)) %>%
  group_by(animal_project_code, release_location) %>%
  count() %>%
  View()
```

animal_project_code | release_location | n
--- | --- | ---
2013_albertkanaal | ~Genenbos~ | 14
2013_albertkanaal | ~Ham~ | 14
2013_albertkanaal | NA | 1
2015_phd_verhelst_cod | ~B05 Belwind~ | 3

**Comment by peterdesmet** [comment]
The release location is the most important:

@IPauwels can you provide the coordinates for Genenbos and Ham?

@jreubens can you provide the coordinates for B05 Belwind?

**Comment by peterdesmet** [comment]
@IPauwels the record with empty release location is animal with tag `A69-1601-64513`, captured on 2017-03-30 10:00:00, hatchery Erezée

**Comment by jreubens** [comment]
done for cod at B05

**Comment by jreubens** [comment]
sorry didn't mean to close it

**Comment by peterdesmet** [comment]
Ham: 51.095625, 5.124383 & Genenbos 51.016, 5.233 are now added.

**Comment by peterdesmet** [comment]
All solved
