### ISSUE TITLE
Use vocabulary for wildOrHatchery

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#12]
The field `wildOrHatchery` expects:

> Enter "wild", "hatchery" or "unknown".

Currently the following values are used:

current value | controlled value | animal project | number of animals | remarks
--- | --- | --- | --- | ---
hatched | hatchery | 2013 Albertkanaal | 62 | corrected
hatchery | hatchery | 2013 Albertkanaal | 29 | ok 
wild | wild | 2011 Rivierprik | 39 | ok
wild | wild | 2012 Leopoldkanaal | 104 | ok
wild | wild | 2013 Albertkanaal | 100 | ok
wild | wild | 2014 Demer | 16 | ok
wild | wild | 2015 Dijle | 26 | ok
wild | wild | 2015 Fint | 39 | ok
wild | wild | 2015 PhD Verhelst | 229 | ok
wild | wild | Homarus | 2 | ok
wild | wild | PhD Jan Reubens | 41 | ok
Wild | wild | 2015 PhD Verhelst | 13 | corrected
WILD | wild | 2013 Albertkanaal | 60 | corrected
(empty) | (to look up) | 2013 Albertkanaal | 45 | corrected
(empty) | (to look up) | 2015 Fint | 5 | corrected

**Comment by peterdesmet** [comment]
@ipauwels @pieterjanverhelst: do you know if the remaining animals in 2013 Albertkanaal and 2015 Fint are wild or from hatchery?

**Comment by PieterjanVerhelst** [comment]
All eels are wild and the salmons are hatchery.

**Comment by peterdesmet** [comment]
@PieterjanVerhelst great. What about Alosa fallax: are those wild or hatchery?

**Comment by PieterjanVerhelst** [comment]
These are all wild.

**Comment by peterdesmet** [comment]
Thanks, all have been corrected.
