### ISSUE TITLE
Use controlled value for lengthType

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#13]
The values for `length_type`, `length2_type`, `length3_type`, `length4_type` are currently free text, but it would be better if these used a controlled vocabulary. I would suggest to use lowercase, e.g. `total length`, which is already the case for most animals.

Table with current values and how to update these (including fixing some typos):

current value | controlled value | projects | animals | remarks
--- | --- | --- | --- | ---
fork lenght | `fork length` | 2013 Albertkanaal | 29 | corrected
horizontal eye diameter | `horizontal eye diameter` | 2015 PhD Verhelst, 2012 Leopoldkanaal, 2013 Albertkanaal | 392 | ok
pectoral fin | `pectoral fin length`| 2013 Albertkanaal, 2015 PhD Verhelst, 2012 Leopoldkanaal | 392 | @fwaumans
total length | `total length` | 2013 Albertkanaal, 2015 PhD Verhelst, 2015 Fint, 2011 Rivierprik, 2012 Leopoldkanaal, PhD Jan Reubens, 2014 Demer, 2015 Dijle, Homarus | 712 | ok
Total length | `total length` | 2015 PhD Verhelst | 21 | corrected
Total Length | `total length` | 2015 Fint | 4 | corrected
vertical eye diameter | `vertical eye diameter` | 2015 PhD Verhelst, 2012 Leopoldkanaal, 2013 Albertkanaal | 346 | ok
verticale eye diameter | `vertical eye diameter` | 2013 Albertkanaal | 45 | corrected

**Comment by peterdesmet** [comment]
@jreubens @pieterjanverhelst Feedback on controlled vocab for length measurement?

**Comment by PieterjanVerhelst** [comment]
I suggest to use `total length`, `fork length`, `pectoral fin length`, `horizontal eye diameter` and `vertical eye diameter`.

**Comment by peterdesmet** [comment]
Thanks! @fwaumans can you update `LENGTH2_TYPE` (153) and `LENGTH4_TYPE` (239) to `pectoral fin length` where it is currently `pectoral fin`?

**Comment by fwaumans** [comment]
The value 'pectoral fin' is replaced by  'pectoral fin length'.

**Comment by peterdesmet** [comment]
Great! Beyond the scope of what is planned to be published, the following values could be updated in `lengthType` as well:

current value | new value | animals
--- | --- | ---
`Total length` | `total length` | 430
`Total Length` | `total length` | 1
`total_length` | `total length` | 5

**Comment by fwaumans** [comment]
@jreubens : we have to discuss if we can change data from dataproviders beyond the scope of lifewatch
