### ISSUE TITLE
Salmo salar: weight without unit

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#14]
44 animals from `2013 Albertkanaal` have a weight without unit (e.g. `A69-1601-34437`). This should be corrected.

**Comment by peterdesmet** [comment]
@ipauwels @pieterjanverhelst. Any idea what unit should be used?

**Comment by PieterjanVerhelst** [comment]
The Salmo salar have weight unit `g`. Note that the sync tags don't have a weight at all.

**Comment by peterdesmet** [comment]
I have added `g` to all Salmo salar, but the values range from `28` to `421.2` grams. Does that seem correct?

![Chart 1](https://user-images.githubusercontent.com/600993/54293198-cba9b180-45af-11e9-9a0c-ebb48b371719.png)

**Comment by PieterjanVerhelst** [comment]
I'll have a check and keep you informed

**Comment by PieterjanVerhelst** [comment]
The lengths and weights are correct: There is indeed a large size-range on the tagged smolts.
