### ISSUE TITLE
Incorrect release date

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#16]
19 animals in `Albertkanaal 2013` have the comment:

> uitzetdatum moet nog aangepast worden; 30 maart is niet juist

This should be corrected:

```
A69-1601-64495
A69-1601-64496
A69-1601-64497
A69-1601-64498
A69-1601-64499
A69-1601-64500
A69-1601-64501
A69-1601-64502
A69-1601-64503
A69-1601-64504
A69-1601-64505
A69-1601-64506
A69-1601-64507
A69-1601-64508
A69-1601-64509
A69-1601-64510
A69-1601-64511
A69-1601-64512
A69-1601-64513
```

**Comment by jreubens** [comment]
This is something that can be done at the webapp. Who of INBO will do this?

**Comment by peterdesmet** [comment]
We now can, but @IPauwels @karenrobberechts: where can we find the correct release date for these animals? They are all `salmo salar` from `kwekerij Erezee`.

**Comment by karenrobberechts** [comment]
Ik heb even rond gehoord bij mijn collega's en ben tot de volgende conclusie gekomen: 
De zalmen zijn allemaal op dezelfde dag gezenderd maar op verschillende dagen uitgezet maar ze weten zelf niet welk gezenderd dier uitgezet is op welke dag. 

Omdat Jenna ze gespreid wilde uitzetten, zijn er 10 uitgezet op 30/3/17, 10/4 nog eens een deel en de laatste op 18/4. Omdat ze allemaal al gezenderd waren en er gestorven zijn (zenders in andere...) zijn de precieze nummers niet gekend. We kunnen ze wel traceren door hun eerste detecties te checken aangezien ze steeds uitgezet in de buurt van een receiver. De eerste uitzetting zijn er bv 5 aan HH5 en 5 SO netwerk uitgezet...

Ik weet niet of jullie dit gemakkelijk uit de databank kunnen halen? Of kan ik dat zelf? Zo ja hoe?

**Comment by peterdesmet** [comment]
Merci voor de info, ik zal es kijken voor de detecties.

**Comment by peterdesmet** [comment]
@karenrobberechts al die transmitters hebben detecties vanaf 30 maart. Sommige stoppen rond 6 april. Hoe kan ik best controleren welke wanneer/waar zijn uitgezet?

**Comment by peterdesmet** [comment]
Discussed with Jenna and resolved in DB.
