### ISSUE TITLE
Use controlled value for captureMethod

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#17]
The values for `capture_method` is currently free text, but it would be better if we used a controlled vocabulary. I would suggest to use **lowercase English names**, e.g. `line fishing` as in suggested in the ETN application. This would then be consistent with `lenghtType`(#13) values.

My suggestion:

captureMethod | controlled value | animals | remarks
--- | --- | --- | ---
Ankerkuil | `stow nets` | 4 | corrected 
fuik | `double fyke nets` | 61 | corrected
Fyke nets | `double fyke nets` | 1 | corrected
FYKE NETS | `double fyke nets` | 265 | @fwaumans
HAND - DIVING | `capture by hand while diving` | 2 | @fwaumans
hand line | `line fishing` | 7 | corrected
Hook and line | `line fishing` | 8 | corrected
Line fishing | `line fishing` | 22 | @fwaumans
LINE FISHING | `line fishing` | 101 | @fwaumans
(empty) | can these be populated? | 339 | 

@pieterjanverhelst @jreubens @ipauwels: suggestions welcome (especially where there are question marks)

**Comment by PieterjanVerhelst** [comment]
*As there are different fyke net types, I would suggest to state ´double fyke nets´ as all animals currently tagged were caught with these type of fyke nets.
*´line fishing´ is appropriate for angling. 
*´Ankerkuil´ = ´stow nets´ (@IPauwels, some time ago, I finally found the correct English term for the method ;-) http://www.fao.org/fishery/geartype/227/en).

**Comment by peterdesmet** [comment]
@PieterjanVerhelst thanks. Table above has been updated with your suggestions. What about `hand line`?

**Comment by PieterjanVerhelst** [comment]
@peterdesmet `hand line` is `line fishing` as well.
`hand catch while diving` could be replaced by `capture by hand during diving`?

**Comment by peterdesmet** [comment]
`during diving` sounds a bit odd to me, used: `capture by hand while diving`.

**Comment by jreubens** [comment]
I agree with the changes made!

**Comment by peterdesmet** [comment]
Great! Can I or @LienReyserhove get access to ETN database to update this field for all projects? If not: who can make the updates?

**Comment by jreubens** [comment]
As mentioned before, I need to discuss this with Filip Waumans.
Is on the agenda for next week ( 11/03). I keep you updated

**Comment by IPauwels** [comment]
Could be something for my colleague, Karen Robberechts, of our team to update the database with the correct terms, but currently she is very busy with field work. So, acces to ETN database for Peter or Lien would be great.
@peterdesmet: you can always contact Karen Robberechts as well and explain her what to do during my absence, just knowing that she is not always available due to the field work.
@PieterjanVerhelst: stow nets!! great :)

**Comment by peterdesmet** [comment]
Ok, will assign to @karenrobberechts or us pending access to database.

**Comment by peterdesmet** [comment]
@fwaumans see the table in the issue body. I've updated the CAPTURE_METHOD where I could, but for the rest I either don't have access (`HAND - DIVING`) or it's too cumbersome to do manually. Can you update the rest to their `controlled value`?

E.g. `FYKE NETS` -> `double fyke nets`

**Comment by fwaumans** [comment]
The field captureMethod is updated with the proposed values.

**Comment by peterdesmet** [comment]
Thanks! 31 records (beyond the scope of what is planned to be published) have values that could be updated too:

current value | new value | records
--- | --- | ---
`Divers, by hand` in Flatfish  | `capture by hand while diving` | 4
`Hook and line` in PhD van der Knaap | `line fishing` | 27

**Comment by fwaumans** [comment]
@jreubens : we have to discuss if we can change data from dataproviders beyond the scope of lifewatch

**Comment by peterdesmet** [comment]
For all data paper projects, this is now ok. Closing issue.
