### ISSUE TITLE
Use controlled value for sex

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#18]
The guideline for the field `sex` is:

> Sex of animal. "M" or "F". Can enter unknown ("U").

This is not the case for all:

sex | controlled value | animals
--- | --- | ---
f | `female` | 60
F | `female` | 367
Female | `female` | 1
M | `male` | 49
(empty) | (empty) | 333

333 have no value. Should we be explicit and set these to `U`?

**Comment by PieterjanVerhelst** [comment]
I suggest to use `male` and `female` (=full written, lower case letters). 
When there is no sex, I suggest to state `NA`

**Comment by peterdesmet** [comment]
I agree, but for no sex would leave the field empty or set to `unknown`. Note that if we take this approach:

- A lot more values need to be updated
- We should request to change the definition of the field

**Comment by peterdesmet** [comment]
@fwaumans @jreubens feedback regarding controlled vocab for sex?

- Lowercase `f`
- Uppercase `F` (current suggestion in ETN app)
- Full lowercase `female` (suggested by @PieterjanVerhelst)

And what to do about unknown values:

- Leave empty
- Set to `U` / `unknown`

**Comment by jreubens** [comment]
I agree with male, female and unknown.
Some updates in the DB are thus needed

**Comment by peterdesmet** [comment]
@fwaumans can you update the values in the database as such:

current value | new value
--- | ---
f | female
F | female
Female | female
M | male
(empty) | unknown

@jreubens @PieterjanVerhelst for the 333 empty values in the DB: is the sex for those missing (should be completed) or unknown?

**Comment by PieterjanVerhelst** [comment]
Only for eels it can be known, for the others it is unknown.
Could you check if there are any empty sex records for eels? Than I'll complete them.

**Comment by peterdesmet** [comment]
9 eels (Albertkanaal) have empty sex. I only know their id_pk:

363
364
704
705
706
707
708
709
2154

**Comment by PieterjanVerhelst** [comment]
@peterdesmet, all are female. I added 'female' to the respective eels in the ETN database.

**Comment by fwaumans** [comment]
The field sex is updated with the proposed values

**Comment by peterdesmet** [comment]
Thanks! 268 records (beyond the scope of what is planned to be published) still have `U`. Might be good to update those as well.

**Comment by LienReyserhove** [comment]
In additon to this, 70 records still have `NA` (beyond scope of the published data)

**Comment by peterdesmet** [comment]
For all projects in the data paper this is now ok. Closing issue.
