### ISSUE TITLE
Include tag in download

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#21]
@fwaumans currently the field `tag` is not included in the **animals download**, even though the field is included in the table:

<img width="686" alt="Screenshot 2019-03-13 at 15 01 55" src="https://user-images.githubusercontent.com/600993/54284869-1243df80-45a1-11e9-8d9f-8d04983c535b.png">

Can this be added as the first field? That would make it easier to reference records. Note that some other tag related fields are already included, such as `tag_end_date`.

**Comment by fwaumans** [comment]
Seems to be a bug. I have to dive in the code.

**Comment by fwaumans** [comment]
Was not a bug. Animal - tag relation is a one to many relationship and is not added automatically. In the rare cases more than one tag is related to an animal a semicolon separated list is given in the tag column , otherwise one tag.
