### ISSUE TITLE
High max for lengths & weight

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#24]
See this [Google spreadsheet](https://docs.google.com/spreadsheets/d/1wupDD9xP1JzV3_GbkdRmRoBfdzM059QmUeQQay3PSxM/edit?usp=sharing) (sheet: "Lengths") and table below: the range (or rather the maximum) for the different types of lengths + weight is sometimes unrealistically high.

@jreubens @PieterjanVerhelst, can you tell me which ones you consider ok?

The rest will have to be corrected in the database, but I don't know what source info to use for that.

## Checklist

* [x] Alosa fallax `total length: cm`: looks ok
* [x] Alosa fallax `weight: g`: wide range
* [x] Anguilla anguilla: `horizontal eye diameter: mm`: very high max **resolved** by using `.`
* [x] Anguilla anguilla: `pectoral fin: mm`: very high max **resolved** by using `.`
* [x] Anguilla anguilla: `total length: cm`: very high max **corrected**
* [x] Anguilla anguilla: `total length: mm`: why not cm? Some researchers add data in cm, others in mm. Flixibility is allowed in this field.
* [x] Anguilla anguilla: `vertical eye diameter: mm`: very high max **resolved** by using `.`
* [x] Anguilla anguilla: `weight: g`: wide range
* [x] Anguilla anguilla: add length type **corrected** to `horizontal eye diameter`
* [x] Cyprinus carpio: `total length: cm`: wide range
* [x] Cyprinus carpio: `weight: g`: wide range
* [x] Gadus morhua: `total length: cm`: very high max **resolved** by using `.`
* [x] Lampetra fluviatilis: `total length: cm`: looks ok
* [x] Lampetra fluviatilis: `weight: g`: looks ok
* [x] Petromyzon marinus: `total length: cm`: looks ok
* [x] Petromyzon marinus: `weight: g`: looks ok
* [x] Platichthys flesus: `total length: cm`: looks ok
* [x] Platichthys flesus: `weight: g`: wide range
* [x] Rutilus rutilus: `total length: cm`: looks ok
* [x] Rutilus rutilus: `weight: g`: wide range
* [x] Salmo salar: `fork length: mm`: looks ok
* [ ] Salmo salar: `total length: cm`: wide range
* [ ] Salmo salar: `weight: g`: very low min
* [x] Salmo salar: add length type: **corrected** to `fork length`
* [x] Silurus glanis: `total length: cm`: very high max, can grow up to 2.5m
* [x] Silurus glanis: `weight: g`: very high max
* [x] Squalius cephalus: `total length: cm`: looks ok
* [x] Squalius cephalus: `weight: g`: looks ok

**Comment by peterdesmet** [comment]
Updated table to also include weight + standard deviation

**Comment by PieterjanVerhelst** [comment]
@peterdesmet, would it be possible to convert the above table in a checkbox? I may not be able to solve all issues at once and a checkbox would help me to keep an overview of what I did and did not tackle.

**Comment by peterdesmet** [comment]
Not really possible to convert table without losing information, but I added a checkbox list at the top.

**Comment by peterdesmet** [comment]
With the correction of #23 I had to update the table and didn't want to do this in two places: opted for Google spreadsheet and removed it from the issue.

**Comment by PieterjanVerhelst** [comment]
:+1:

**Comment by PieterjanVerhelst** [comment]
@peterdesmet, I cannot find the eels with the wronlgy max `horizontal eye diameter`, `vertical eye diameter` and `pectoral fin`. Could you just give me the transmitter ID and project name of the eels with such a max? Than I will be able to check if some other eels have a wrong max as well.
Note that the column `Length2_type` is either `horizontal eye diameter` or `pectoral fin length`, depending on the project. Obviously, this also holds true for the other length types.

**Comment by peterdesmet** [comment]
I don't have the transmitter ID, because that is not yet exported (see #21), but I do have the ID. Example: `2299` which has `horizontal eye diameter` = `12,95`.

I see now that it's the comma as decimal separator that is causing the issue (interpreted as 1295). A period should be used instead: `12.95`. A quick check indicates that a `,` is used:

column | animals | remarks
--- | --- | ---
length | 1 | corrected
length2 | 47 | 
length3 | 48 | 
length$ | 51 | 

I'll correct those and rerun the numbers.

Regarding your note: Yes, I combined all length variables into a single column + type + unit, so i don't have to check over the 4 columns.

**Comment by peterdesmet** [comment]
@PieterjanVerhelst values corrected and spreadsheet updated.

**Comment by PieterjanVerhelst** [comment]
@peterdesmet. Could you check if the total lengths of `Anguilla anguilla` are now within realistic ranges?
The only two lines I am still trying to find out, are length and weight of `Salmo salar`.

**Comment by peterdesmet** [comment]
There is still one massive shrieking eel of 5m `A69-1601-58620` and one (probably ok) of `102cm`: `A69-1601-26465`

In addition to the two lines for Salmo salar: is the weight range for Anguilla anguilla ok?

**Comment by PieterjanVerhelst** [comment]
Shrieking eel `A69-1601-5820` is adjusted ant the others are correct :-). We caught some massive eels in the Albert Canal, with that one of `102 cm` and `2241 g` one of the biggest I've ever seen!
As such, the weight range for `Anguilla anguilla` is ok.

**Comment by peterdesmet** [comment]
@PieterjanVerhelst any feedback on the weights/lengths of Salmo salar? If approved than we can close this issue.

**Comment by PieterjanVerhelst** [comment]
@peterdesmet, no info obtained. I will send a reminder to the involved researchers.

**Comment by peterdesmet** [comment]
> I will send a reminder to the involved researchers (regarding weights/lengths of Salmo salar)

@PieterjanVerhelst see comment above (from over a year ago): can this issue now be closed?

**Comment by PieterjanVerhelst** [comment]
@peterdesmet can be closed. Note that form Salmo salar lengths are either in mm or cm (indicated in the column `Length1_unit`).
