### ISSUE TITLE
Update length type suggestions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#25]
In light of #13, please update the `as in` examples in the application to their lowercase variants:

## length_type

![Screenshot 2019-03-14 at 11 20 55](https://user-images.githubusercontent.com/600993/54349472-9c488280-464b-11e9-9640-64d3e5ca6494.png)

Change to `as in: total length`

## lenght2_type

![Screenshot 2019-03-14 at 11 21 12](https://user-images.githubusercontent.com/600993/54349447-90f55700-464b-11e9-8241-82bf06a4c335.png)

Change to `as in: horizontal eye diameter`

## length3_type

![Screenshot 2019-03-14 at 11 21 23](https://user-images.githubusercontent.com/600993/54349454-93f04780-464b-11e9-9713-d4ff6f7c0d8a.png)

Change to `as in: vertical eye diameter`

## length4_type

![Screenshot 2019-03-14 at 11 21 31](https://user-images.githubusercontent.com/600993/54349460-9652a180-464b-11e9-8c37-18800ca07ac4.png)

Change to `as in: pectoral fin length`

**Comment by fwaumans** [comment]
@jreubens will change these descriptions.

**Comment by jreubens** [comment]
Done!
