### ISSUE TITLE
Eels with incomplete measurements

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#26]
@pieterjanverhelst Of the 402 eels there are 11 that do not have all 4 measurements. Can this information be completed (especially for the first 2-3 that have the other measurements)?

tag | project | length_type | length2_type | length3_type | length4_type
--- | ---| ---| ---| ---| ---
A69-1601-31899 | 2012 Leopoldkanaal | total length | horizontal eye diameter | | | 
A69-1601-47322 | 2013 Albertkanaal | total length | pectoral fin | horizontal eye diameter
A69-1601-28261 | 2013 Albertkanaal | Anguilla anguilla | total length |  |  | 
A69-1601-28262 | 2013 Albertkanaal | Anguilla anguilla | total length |  |  | 
A69-1601-28263 | 2013 Albertkanaal | Anguilla anguilla | total length
A69-1601-34461 | 2015 Dijle | Anguilla anguilla | total length |  |  | 
A69-1601-26524 | 2013 Albertkanaal | Anguilla anguilla | total length |  |  | 
A69-1601-26525 | 2013 Albertkanaal | Anguilla anguilla | total length |  |  | 
A69-1601-26528 | 2013 Albertkanaal | Anguilla anguilla | total length |  |  | 
A69-1601-28259 | 2013 Albertkanaal | Anguilla anguilla | total length |  |  | 
A69-1601-28260 | 2013 Albertkanaal | Anguilla anguilla | total length |  |  |

**Comment by PieterjanVerhelst** [comment]
For `A69-1601-31899` there is no data for all 4 length types (only total length). Eel `A69-1601-47322` I added the missing info of the 4 length types.
For the others, I do not have the data but will try to find out and complete the list.

**Comment by PieterjanVerhelst** [comment]
Information for `A69-1601-34461` was added as well.
BTW, the buttons on my github do not work anymore (cannot edit previous posts, nor assign people, use quick-buttons in message boxes...). Did try another web browser, but problem persists.

**Comment by peterdesmet** [comment]
@PieterjanVerhelst regarding GitHub and you were able to do this before **in this repository**? Anyway, I have given you @jreubens @IPauwels write access to this repo, which will probably allow you to at least assign people and label issues.

**Comment by PieterjanVerhelst** [comment]
@peterdesmet, no I was never able to do this in this repo, and it is a few months now I can't in my own repos as well. Probably has something to do with my browser settings?

**Comment by peterdesmet** [comment]
Difficult to assess without seeing what the problem is, but sounds weird.

**Comment by PieterjanVerhelst** [comment]
When I am at inbo, I'll drop by for a quick look ;-).

**Comment by PieterjanVerhelst** [comment]
For the 8 eels of `Albertkanaal 2013` there is no data on the different length measures as well.
So in conclusion:
For 2 eels (`A69-1601-34461` and  `A69-1601-47322`) I added the information.
For the 1 eel `A69-1601-31899` from `2012 Leopoldkanaal` and the 8 eels from `Albertkanaal 2013` there is no additional measurement data.

**Comment by peterdesmet** [comment]
Information assumed complete.
