### ISSUE TITLE
Make length + weight doubles

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#27]
The fields:

- `LENGTH`
- `LENGTH2`
- `LENGTH3`
- `LENGTH4`
- `WEIGHT`

Are indicated as being `format: double`:

![Screenshot 2019-03-14 at 16 16 21](https://user-images.githubusercontent.com/600993/54368539-a5017e80-4674-11e9-9cff-45cba72bc92b.png)

One can enter text strings in those fields though. These leads to errors, e.g. `,` and `.` being used as decimal separators (caused #24).

@fwaumans can those fields be set to double + returning an error if a value does not comply.

**Comment by fwaumans** [comment]
The fields LENGTH, LENGTH2, LENGTH3, LENGTH4, WEIGHT are converted to double

**Comment by peterdesmet** [comment]
Great!
