### ISSUE TITLE
Update example for field sex 

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#28]
<img width="482" src="https://user-images.githubusercontent.com/600993/54982130-4f996b80-4faa-11e9-9cdd-9b706cf5f917.png">

See #18: the recommended values are now:

```
male
female
unknown
```

Can the example in the help text be updated?

> **Definition**
> Sex of the animal. "male", "female" or "unknown".
> 
> **Units/format example**
> `as in: female`

**Comment by fwaumans** [comment]
@jreubens  will change this in the webapplicaton.

**Comment by jreubens** [comment]
Done
