### ISSUE TITLE
Unique identifiers for animals

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#30]
The field `animal_id` appears to be to best field for unique identifiers:
> Identification code that uniquely identifies each animal, as specified by the researcher.

However, this field is often empty, which makes it useless as a unique identifier.
Decided to take `id_pk` instead, but see #29

**Comment by peterdesmet** [comment]
@PieterjanVerhelst @jreubens I think we have discussed unique identifiers for animals before, but since none were given I seem to remember that using the internal `id_pk` (guaranteed unique, because set by database) is sufficient?

**Comment by PieterjanVerhelst** [comment]
If `id_pk` is indeed a unique number automatically attributed by the database, I would say yes, we can use that ID. But @jreubens can give more information about this database step.

**Comment by jreubens** [comment]
animal_id is no unique identifier, this is filled in when you for example have an external tag with a specific number. id_pk is the unique one...

**Comment by LienReyserhove** [comment]
OK, thx!
