### ISSUE TITLE
dwc_animals.Rmd: structure and term overview

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#31]
The focus of  `dwc_animals.Rmd` is to map the animal metadata, i.e. data related to capture, release and surgery of the fish. The _structure_ of the mapping is rather complex and involves mapping to the [Event Core](https://tools.gbif.org/dwca-validator/extension.do?id=dwc:Event), [Occurrence Extension](https://tools.gbif.org/dwca-validator/extension.do?id=dwc:Occurrence) and [extended Measurement of Facts Extension](https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact) (eMoF). 
In this issue I give an overview of
- How I think the Core and extension file relate
- Which terms can be assigned to the core or extension file

The occurrenceID's  and eventID's are composed of:
- `projectname`: name of the animal project 
- `id_pk`, which is the unique identifier for a specific animal (within and across animal projects)
- `occurrence` or `event`
- `capture`, `surgery` or `release`

Note: 
> _the release Event record does not represent a distinct Occurrence record from the capture event. Holding periods, movement of the animal while captured, and other confounding circumstances preclude this record from being considered a natural occurrence of the animal_, see [this page](https://github.com/tdwg/dwc-for-biologging/wiki/Acoustic-sensor-enabled-tracking-of-blue-sharks)

Legend: 
In blue, red or yellow: the Darwin Core terms, belonging to respectively the event core, occurrence extension or eMoF extension, in grey the column names from the raw data file. 

![Scheme dwc_animals Rmd_slide1](https://user-images.githubusercontent.com/32466479/58021128-68398400-7b0a-11e9-9222-4c14ee97b3b5.jpg)
![Scheme dwc_animals Rmd_slide2](https://user-images.githubusercontent.com/32466479/58021136-6bcd0b00-7b0a-11e9-9b85-7358ed7d0ea7.jpg)

**Comment by peterdesmet** [comment]
Nice schema! Some feedback:

- [x] Relate the tag properties to the surgery event, not capture
- [x] Remove `eventTime`: time information is to be included in `eventDate`
- [x] Point arrows in other direction: relation is from extension to core
- [x] Remove `individualCount`
- [x] Switch `type` and `value` for length, e.g. `mType` = `length2_type`
- [x] Don't use underscores in `mType` names, e.g. use `wild or hatchery`
- [x] `holding period` should have a unit (e.g. hours)
- [x] Altogether remove the second `Occurrence capture`
- [x] I would combine the capture and surgery (= tagging) event: there is no field `date_of_surgery` and `surgery_lat/long` are empty in 95% of the cases, so it's not possible to create separate events for these. **See #33: there is a field `date_of_surgery`: Decided to keep surgery separate. Not sure if all records have a surgery date**

Questions:

- [x] Should `samplingProtocol` also be included in `MoF` and if yes, for capture event or occurrence?
- [x] Should `verbatimDepth` also be included in `MoF` and if yes, for capture event or occurrence?

**Comment by PieterjanVerhelst** [comment]
Date differences between capture and surgery event can occur, especially since it is sometimes required to move a fish to a facility and keep in quarantine. Although we (inbo, vliz and ugent) do not apply such measures, (1) I think keeping track of both capture and surgery event explicitly clarifies this and (2) in some occasions fish (I think eels from the Albertkanaal) were not tagged immediately upon catching.

Do do you mean with `samplingProtocol` only the catch method (e.g. fyke nets, stow nets...) or also details related to the surgery?
What do you mean with `verbatimDepth`?

**Comment by peterdesmet** [comment]
@PieterjanVerhelst I updated my comment regarding surgery, but see especially https://github.com/inbo/etn-occurrences/issues/33

Regarding `samplingProtocol` (yes, those values) and `verbatimDepth`: these were more technical reminders for myself. 😄

**Comment by LienReyserhove** [comment]
Thanks for the feedback, I already made some adjustments in the schema and will integrate the suggestions in the mapping accordingly. 
I get the point with respect to the capture and surgery event, it doesn't make any sense if no date is provided for surgery (didn't check, sorry) and if surgery location is often identical to capture location. I'm awaiting the response in #33 to integrate these suggestions into the scheme. 
I would however still use `capture` as the main event instead of `tagging`. This would better correspond with the natural capture occurrence.

**Comment by LienReyserhove** [comment]
and with respect to `verbatimDepth`: this field appears to be empty so not relevant for this publication

**Comment by PieterjanVerhelst** [comment]
Capture and surgery location often differ from each other, so should be kept separate.

Regarding `samplingProtocol`, what do you mean with 'occurrence'? This is a detection? If so, it is only relevant for the capture event.

**Comment by peterdesmet** [comment]
`samplingProtocol` can be kept where it is: as a property about the capture event (and thus occurrence).
