### ISSUE TITLE
Why is there surgery location/lat/long if there is no surgery date?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#33]
@PieterjanVerhelst @jreubens 

I noticed that it is possible to define a `surgery location` (+ latitude and longitude), but not a `surgery date`. That means you cannot define a separate surgery event.

If the `surgery date` is assumed to be the `capture date`, can't we assume the same for `surgery location` then? **That would reduce the amount of metadata that needs to be managed.** It looks like it is used as such anyway: it is populated for 47% of the records, but is almost always the same as the `capture location`. Here are the records where it is different:

captureLocation | surgeryLocation | animals
--- | --- | ---
D1 | D5 | 3
D3 | D5 | 2
D6 | D5 | 2
D6 | tss D5 en D6 | 1
D6 | tussen D5 en D6 | 1
KLEINE KIL | LEOPOLDKANAAL (NOORDSTRAAT) | 9
SS Auretta | SS Auretta (wrak 224) | 1
Wrak Bruno Heinemann | Bruno Heinemann | 1

I would suggest to either:

- Have `surgery location` AND `surgery date`
- Have neither (closest to the current use and my preference)

**Comment by PieterjanVerhelst** [comment]
@peterdesmet, there is a field in the ETN database with the surgery date: `date of surgery`.
The most important part for interested users of the data to my opinion, is that they know where the fish were caught and released. The surgery information is maybe to exhaustive to include in the data-publication and when wanted, could be obtained by contacting the appropriate researcher?
@jreubens, what do you think?

**Comment by LienReyserhove** [comment]
I'm not fond of leaving out the surgery data out of the published dataset. 
In my opinion, the published dataset should contain as much relevant information as possible, which includes the surgery data.

**Comment by PieterjanVerhelst** [comment]
Agree, than we include them :-)

**Comment by jreubens** [comment]
agree to have it included

**Comment by peterdesmet** [comment]
My bad, I overlooked the field. 😬It is not included in the export. Will report this separately.

**Comment by LienReyserhove** [comment]
There's still the problem that `date_of_surgery` is empty for about 57% of the events and `surgery_latitude` and `surgery_longitude` are always empty (for the data within the publication scope). Especially in case of date information this is problematic as this information is obligatory. I assume this is because most individuals didn't have any surgery? 
We could limit the surgery event to records for which `date_of_surgery` is provided.

**Comment by peterdesmet** [comment]
I assume it is because for most animals the surgery took place at the same loc/time as the capture and/or release. Still: best if that info is completed in ETN DB.

**Comment by LienReyserhove** [comment]
Indeed, in all cases, `surgery_location` is equal to `capture_location` or to `release_location`.
Thus, for almost all surgery cases, we can adopt location and coordinates from the release event. For the two specific cases below, we have to adopt location and coordinates from the capture event.
I will make a separate issue for this and assign it to @fwaumans 

1. Surgery location is not capture location: 

| id_pk|projectname        |scientific_name   |surgery_location            |capture_location |release_location            |
|-----:|:------------------|:-----------------|:---------------------------|:----------------|:---------------------------|
|   438|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   444|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   445|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   446|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   447|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   448|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   451|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   456|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
|   457|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (NOORDSTRAAT) |KLEINE KIL       |LEOPOLDKANAAL (NOORDSTRAAT) |
2. Surgery location is not release location

| id_pk|projectname        |scientific_name   |surgery_location                 |capture_location                 |release_location |
|-----:|:------------------|:-----------------|:--------------------------------|:--------------------------------|:----------------|
|   458|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (STENENSCHUURBRUG) |LEOPOLDKANAAL (STENENSCHUURBRUG) |LEGEMEERSBEEK    |
|   459|2012 Leopoldkanaal |Anguilla anguilla |LEOPOLDKANAAL (STENENSCHUURBRUG) |LEOPOLDKANAAL (STENENSCHUURBRUG) |LEGEMEERSBEEK    |

**Comment by jreubens** [comment]
Surgery locations for 'PhD Jan Reubens' have been updated
