### ISSUE TITLE
Cleanded content for capture locations

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#34]
The current values in `capture_location` should be cleaned somewhat before mapping to the DwC term `locality`. I suggest the following actions (see also #41 for cleaning of release_location and #42  for cleaning of surgery_location)

1. Restrict the use of capital letters (only when required)

|capture_location                        | records|capture_location_clean | OK
|:---------------------------------------|--------|---------------------------------|-----:|
|ABANDONNED FYKES (?)                    |       5|abandonned fykes (?)     
|BOEREKREEK                              |       7|Boerekreek |OK
|DIJLE (STUW. MECHELEN NEKKERSPOEL)      |       9|Dijle (weir Mechelen Nekkerspoel) |OK
|FISH WAY ASPER                          |       1|fishway Asper |OK
|FISHWAY ASPER                           |       5|fishway Asper  |OK
|FISHWAY MERELBEKE                       |       1|fishway Merelbeke   |OK
|FISHWAY OUDENAARDE                      |       2|fishway Oudenaarde   |OK
|GROTE GEUL                              |      10|Grote Geul | OK
|ISABELLAGEMAAL                          |      28|Isabellagemaal|OK
|KLEINE KIL                              |       9|Kleine Kil|OK
|LEGEMEERSBEEK                           |       6|Legemeersbeek |OK
|LEOPOLDKANAAL (FRED'S CAFE)             |       8|Leopoldkanaal (Fred's café) |OK
|LEOPOLDKANAAL (OESTERPUT)               |       3|Leopoldkanaal (Oesterput)    |OK 
|LEOPOLDKANAAL (STENENSCHUURBRUG)        |      15|Leopoldkanaal (Stenenschuurbrug) |OK
|LEOPOLDKANAAL (WATERVLIET)              |       8|Leopoldkanaal (Watervliet)   |OK
|sluis genk                              |      36|shipping lock Genk|OK
|WEIR ASPER                              |       2|weir Asper  |OK
|WEIR GUTTER ASPER                       |       5|weir gutter Asper |OK
|WEIR MERELBEKE                          |       8|weir Merelbeke |OK
|ZEESCHELDE (BERGENMEERSEN. WICHELEN)    |       4|Zeeschelde (Bergenmeersen, Wichelen)  |OK
|ZEESCHELDE (KILLEWEG. DENDERMONDE)      |       2|Zeeschelde (Killeweg, Dendermonde)   |OK
|ZEESCHELDE (LEPELSTRAAT. RUPELMONDE)    |       2|Zeeschelde (Lepelstraat, Rupelmonde) |OK
|ZEESCHELDE (RINGVAART. MERELBEKE)       |     111|Zeeschelde (ringvaart, Merelbeke)|OK
|ZEESCHELDE (VEERBOOT. KASTEL)           |       7|Zeeschelde (veerboot, Kastel) |OK
|ZWARTESLUISBEEK                         |      10|Zwartesluisbeek|OK

2. Use correct encoding and shorten lengthy location names

|capture_location                                                                                                                           | records|capture_location_clean | OK
|:------------------------------------------------------------------------------------------------------------------------------------------|--------|---------------------------|------:|
|Erezée: Salmoniculture du Service Public Wallon (SPW) située à Erezée.                                                                     |      44|hatchery Erezée|OK
|Ereze: Salmoniculture du Service Public Wallon (SPW) situe  Ereze. Les poissons proviennent de la production de smolts 2013.               |      56|hatchery Erezée|OK
|kwekerij Erezee                                                                                                                            |      29|hatchery Erezée|OK
|Lorc Ambleve                                                                                                                               |       2|Lorcé Amblève|OK
|Lorc Amblve                                                                                                                                |       1|Lorcé Amblève|OK
|Lorcé Amblève                                                                                                                              |       1|Lorcé Amblève|OK
|Lorcé Amblève                                                                                                                              |       1|Lorcé Amblève|OK
|Mry : Pige de dvalaison sur l'Ourthe (affluent de la Meuse) situ sur le barrage de Mry  12km en amont de la confluence avec la Meuse       |       6|upstream the Méry dam in the River Ourthe|OK

3. Provide full names instead of abbreviations for `stroomopwaarts` and `stroomafwaarts`

|capture_location                     | records|capture_location_clean | OK
|:------------------------------------|--------|----------------------------------------|-------:|
|fuik brug Demer verder SO steunbeer  |       1|Bridge River Demer upstream artificial construction Steunbeer |OK
|sa stuw Mechelen                     |       1|Downstream weir Mechelen|OK
|SA stuw Mechelen                     |       2|Downstream weir Mechelen|OK
|SO Diepenbeek afvoerriool            |       3|Upstream draining channel Diepenbeek|OK
|SO Genk afvoerriool                  |      25|Upstream draining channel Genk  |OK
|SO Hasselt afvoerriool               |      10|Upstream draining channel Hasselt|OK
|so steunbeer                         |       1|Upstream artificial construction Steunbeer  |OK
|SO stuw Mechelen                     |      21|Upstream weir Mechelen|OK
|verder so steunbeer                  |       3|Further upstream artificial construction Steunbeer|OK

4. Give more information for some of the locations

|capture_location       | records|capture_location_clean                          | OK
|:----------------------|--------|----------------------------------|-------------:|
|D1                     |       3|wind turbine D1 C-Power|OK
|D3                     |       2|wind turbine D2 C-Power|OK
|D5                     |      15|wind turbine D5 C-Power|OK
|D6                     |      21|wind turbine D6 C-Power|OK
|VLVS - Zone 2.2        |       1| Drowned Land of Saeftinghe|OK

**Comment by jreubens** [comment]
D3 and D5 can be replaced by 'D3 C-Power' and 'D5 C-Power'

**Comment by PieterjanVerhelst** [comment]
`D3` and `D5` are wind turbines, so I suggest to name them `wind turbine D3` and `wind turbine D5`
`VLVS - Zone 2.2` is an eel caught at the Drowned Land of Saefthinge at the IJskelder ditch. I suggest to call it `ijskelder Saeftinghe`
`stroomaf 2 bruggen meest SA bocht` is from a project @IPauwels was working on, so I let her decide for this one.

**Comment by LienReyserhove** [comment]
And of course for `release_location`:
- Only use capital letters when absolutely necessary
- What does HH5 and M-4-1 stand for?
- Provide full names for LO, RO, SO and SA

Some examples:

|release_location                                                                      | records|
|:-------------------------------------------------------------------------------------|-------:|
|NA                                                                                    |       2|
|BOEREKREEK                                                                            |       7|
|D5                                                                                    |      22|
|D6                                                                                    |      17|
|DIJLE (STUW. MECHELEN NEKKERSPOEL)                                                    |       9|
|HH5                                                                                   |      86|
|Jachthaven Genk SO complex                                                            |       5|
|LO Demer ter hoogte van receiver in Demer aan monding Zwarte beek                     |       1|
|M-4-1 (LO)                                                                            |      17|
|M-4a-1 (RO)                                                                           |       2|
|M-4 (LO)                                                                              |       7|
|Ongeveer 100m bovens stuw Asper in sterk stromende stuwgeul :-(                       |       3|
|SA Asper (niet tijarm!)                                                               |       1|
|SA Grosse Batte Ourthe                                                                |      15|
|SO pompgemaal Ham                                                                     |       1|
|tss D5 en D6                                                                          |       1|
|tussen D5 en D6                                                                       |       1|

**Comment by LienReyserhove** [comment]
Thank you for the input. I adjusted the table above with all locality information that needs cleaning. 
@jreubens , @PieterjanVerhelst  and @IPauwels  could you please verify these suggestions? 
When approved, I will inform Filip to do the transformation.

**Comment by jreubens** [comment]
I agree with the wind turbine suggestions. All the others are INBO related, I leave that up to INBO people

**Comment by PieterjanVerhelst** [comment]
Further suggestions (just conform using English nomenclature instead of dutch) (must admit that many are not very meaningful for people not involved in the project, though):

sluis Genk = shipping lock Genk
kwekerij Erezée = hatchery Erezée
Piège de dévalaison sur l'Ourthe situé sur le barrage de Méry en amont de la confluence avec la Meuse = upstream the Méry dam in the River Ourthe
fuik brug Demer verder stroomopwaarts steunbeer = Bridge River Demer upstream artificial construction Steunbeer
stroomafwaarts stuw Mechelen = Downstream weir Mechelen
stroomopwaarts Diepenbeek afvoerriool = Upstream draining channel Diepenbeek
stroomopwaarts Hasselt afvoerriool = Upstream draining channel Hasselt
stroomopwaarts steunbeer = Upstream artificial construction Steunbeer
stroomopwaarts stuw Mechelen = Upstream weir Mechelen
verder stroomopwaarts steunbeer = Further upstream artificial construction Steunbeer

"ABANDONNED FYKES (?)" I have no clue where that is. @IPauwels will have to comment on that.

**Comment by LienReyserhove** [comment]
Thanks for the suggestions.
I suppose that most of the data is now ok. Just `abandonned fykes (?)`, which will have to be checked by @IPauwels .
As this only concerns 5 records, I suggest these adaptations can be made in the db.
@fwaumans could you integrate the abovementioned adaptations please?

**Comment by fwaumans** [comment]
I have updated the field `capture_location`
