### ISSUE TITLE
Include DATE_OF_SURGERY in table and download

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#35]
Cf. #22. @fwaumans can you add the field `DATE_OF_SURGERY` in the list of available fields to show in the **animals table**:

<img width="229" alt="Screenshot 2019-03-13 at 14 59 06" src="https://user-images.githubusercontent.com/600993/54284994-57681180-45a1-11e9-9c2f-9ae81ec2a035.png">

Can you add it to the data download as well?

**Comment by fwaumans** [comment]
DATE_OF_SURGERY added in available field and data download.

**Comment by peterdesmet** [comment]
Thanks.
