### ISSUE TITLE
Multiple tags for single animal

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#36]
Some animals have multiple tags, e.g.:

```
"A69-9006-905;A69-9006-906,"2015 PhD Verhelst","2018-02-13 11:00","Gadus morhua"
```

We will have to figure out if those tags are added in sequence or at the same time and how the surgery date relates to these (first/latest).

@PieterjanVerhelst any insights on multiple tags for single animals?

**Comment by PieterjanVerhelst** [comment]
@peterdesmet @LienReyershove, some tags have sensors and each sensor comes with a seperate tag-ID. In the case you mention, both IDs (`A69-9006-905` and `A69-9006-906`) belong to the same tag and therefore fish.
However, it can occur that a tag is being retrieved and used in another fish. For instance tag ID ` A69-1601-29920`, which involves an eel being tagged in `2012 Leopoldkanaal`, than caught, tag retrieved and used for an eel in `2013 Albertkanaal`. Both eels have, however, a different catching date and location. Does this still pose a problem?

**Comment by LienReyserhove** [comment]
I don't think this is a problem as the ID of the tag should not be unique, the ID of the individual on the other hand should be unique.
