### ISSUE TITLE
geodeticDatum and coordinate uncertainty

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#37]
I assume that the `geodeticDatum` upon which the coordinate system is based is `WGS84`?

With respect to the coordinate uncertainty:
> The horizontal distance (in meters) from the given decimalLatitude and decimalLongitude describing the smallest circle containing the whole of the Location. Leave the value empty if the uncertainty is unknown, cannot be estimated, or is not applicable (because there are no coordinates). Zero is not a valid value for this term.

Best practise is to populate this field. For Darwin Core, 30 is the suggested number:
> 30 (reasonable lower limit of a GPS reading under good conditions if the actual precision was not recorded at the time).

Is this reasonable?

**Comment by peterdesmet** [comment]
It is reasonable if a GPS is used to find the location. I don't know if that is what was done in the field. @PieterjanVerhelst ?

**Comment by PieterjanVerhelst** [comment]
Coordinates are indeed in `WGS84`. These are determined in two ways:
- hand GPS (garmin)
- through google maps

Is '30' still feasable?

**Comment by LienReyserhove** [comment]
I had a quick google search on the coordinate precision of google maps, and from what I can find, the coordinate uncertainty is less then 30 meters. Some mention around 30 feet (which is about 10 meters). So two options:

1. We can keep the 30m imprecision, which is probably ok and might even be too large
2. We do not integrate `coordinateUncertaintyInMeters` in the DwC mapping. 

I think option two is the most correct one.
Another way could be to figure out which coordinates are deterimined using google maps and leave these fields empty. But no idea if this can be reconstructed. 
@peterdesmet suggestions?

**Comment by peterdesmet** [comment]
It's always better to provide a (too big) `coordinateUncertaintyInMeters` than none at all. We know it's between 10 and 30 meters, but a user of the data doesn't. Maybe it's 1000m?

So, I would keep `30m`: it is recognized in the community as a safe value for GPS.
