### ISSUE TITLE
Lacking values for person_id

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#38]
Some of the records in the dataset have no person_id assigned to the capture/release/surgery event.
In the subset prepared for publication, this concerns 86 animals, all belonging to the animal project `2013 Albertkanaal`. Can this information be supplied? 

We will map `person_id` to the Darwin Core term `recordedBy`. The specification for this field is:
> A list (concatenated and separated) of names of people, groups, or organizations responsible for recording the original Occurrence. The primary collector or observer, especially one who applies a personal identifier (recordNumber), should be listed first.

Ideally, we want the full name of the person here. Is this an option?

**Comment by LienReyserhove** [comment]
Fyi, for the whole dataset (animals), about 50% of the values for `person_id` is empty

**Comment by peterdesmet** [comment]
The field `tagger` is empty for all animals in the data paper and thus not linked to `person_id`. I think that is fine.
