### ISSUE TITLE
Tag information in surgery event

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#39]
As described in the mapping scheme in #31, tag information will be related to the capture event.
While deciding which tag properties to include, I encountered several problems/issues:

### Which tag information is required?

Tag information can be found in two different metadata overviews generated by the etn-package:
- Animal overview
- Transmitter overview

Below I made an attempt to extract field names with potentially interesting information to include (for an overview of all available terms see attached images) :

- Animals overview:
  - `tag_code_space`
  - `end_date_tag`
  - `animal_tag_release_id_pk`
  - `thelma_converted_code`
  - `tag_full_id`

![prinscreen my_animals](https://user-images.githubusercontent.com/32466479/55801951-7cd03880-5ad7-11e9-819a-76ae563de499.png)

- Transmitter overview:
  - `serial number`
  - `type`
  - `model`
  - `idCode`
  - `estimated_lifetime`
  - `acoustic_tag_type`
  - `frequency`

![prinscreen my_tags](https://user-images.githubusercontent.com/32466479/55802139-e81a0a80-5ad7-11e9-9259-a88cfa9311ee.png)

Suggestions/comments are welcome

### Confusing and lacking field definitions

It is very difficult for me to figure out what information to include as some of the field names in the overviews generated by the etn-package are not included in the field definitions (e.g. `animal_tag_release_id`), or included under a different name (`tag_full_id`, which is `tag` in the field definitions file) or included but not defined (e.g. `thelma_converted_code`). This is a general problem and I will make a different issue for this later.

**Comment by PieterjanVerhelst** [comment]
@jreubens, is it necessary to include `thelma_converted_code`? What does this say (no experience with Thelma tags...)?
I would also include information about the different steps, energy output and sensors.

**Comment by peterdesmet** [comment]
@LienReyserhove it will be related to the surgery event, not capture.

Here's an overview of all tag related fields in both tables:

tags | animals | example | remarks
--- | --- | --- | ---
serial_number | - | 1249187 | 
type | - | Acoustic | 
model | - | V13-1x | 
id_code | - | 52656 | 
tag_code_space | tag_code_space | A69-1601 | 
owner_pi | - | PIETERJAN VERHELST | 
id_pk | - | 1370 | 
\- | animal_tag_release_id_pk | 1309 | no idea what this is
min_delay | - | 60 | 
max_delay | - | 100 | 
power | - | H | 
\- | end_date_tag | 2019-09-11 13:30:00 | unrelated to `end_date` it seems
file | - | tagsheet_21464.csv | 
estimated_lifetime | - | 1021 | 
\- | est_tag_life | NA | unrelated to `estimated_lifetime` it seems
sensor_type | - | NA | 
frequency | - | 069k | 
acoustic_tag_type | - | animal | 
min_delay_step2 | - | NA | 
max_delay_step2 | - | NA | 
power_step2 | - | NA | 
power_step3 | - | NA | 
duration_step1 | - | NA | 
duration_step2 | - | NA | 
duration_step3 | - | NA | 
manufacturer_fk | - | 1 | 
owner_group_fk | - | 6 | 
financing_project_fk | - | NA | 
sensor_transmit_ratio | - | NA | 
tag_full_id | tag_full_id | A69-1601-52656 | 
status | - | ACTIVE | 
projectcode | projectcode | 2015_phd_verhelst | probably unrelated

I think we will have to select what tag information to include in DwC and maybe make the full metadata overview accessible somewhere. @jdpye, how do you tackle this for OTN?

**Comment by jdpye** [comment]
Our original method of just reporting occurrences at release locations is being remade to include all the other things we find important about the tag.

Good to include the full tag ID, its serial, its vendor (as Thelma/Vemco tags can be detected on Vemco equipment) the frequency of transmission (69k, 180k, etc), and the estimated tag life (mainly a function of the battery size and the tag programming, estimate provided by the vendor). The Thelma translated tag ID would be how a Thelma receiver records it, which is mappable to the Vemco codes but not expressed the same way, so we would include that as well for Thelma tags. The acceleration data would be farmed out to a set of EMoF entries like any other sensor, and (I think?) that's how we arehandling the ping interval programming as well, so all the *_step_* data would be recorded that way.

sensor_type's a description of whether and what sort of additional sensor is w/ the tag, so where it exists, we use general entries from NERC to point to what we're talking about. P01 has the stuff for oceanographic sensors, P10 for standard acoustic telemetry equipment.

I don't have hard rules for what goes where in DwC terms yet. Happy to take direction as I add this information to the OBIS-ENV-DATA example sets.

**Comment by LienReyserhove** [comment]
@jdpye I tried to distill the following information related to **tag properties** (i.e. technical aspects):

tags | animals | example | 
--- | --- | ---
tag_full_id | tag_full_id | A69-1601-52656 | 
serial_number | - | 1249187 | 
manufacturer_fk | - | 1 |
frequency | - | 069k | 
estimated_lifetime | - | 1021 |  
sensor_type | - | P | 

Note: 
- Thelma converted code only includes `NA`, not integrated in EMoF
- `manufacturer_fk` refers to the ID of the vendor

I'm not 100% sure if I understand the essence here:

> The acceleration data would be farmed out to a set of EMoF entries like any other sensor, and (I think?) that's how we arehandling the ping interval programming as well, so all the step data would be recorded that way.

Note: we have no acceleration data, I removed these fields from the table.

**Do you mean that**
1. We need to include the **detections data** , i.e. the **value** recorded by the tag, into the EMoF extension? 
2. We need to include the **technical specifications** related to the steps (pings?) into the EMoF extension, which is a property of the **tag** rather than the **detections**

We will consider both types of data anyway, but at this point in the mapping process, we are focusing on the mapping of the **metadata**, i.e. map all information related to the capture, release and surgery event, which requires the integration of the tag properties into the EMoF extension. 

I assume your specific comment relates to the second point, including the technical specifications of the tag, which means that we can include the following information:

tags | animals | example | 
--- |--- |--- |
min_delay | - | 60 | 
max_delay | - | 100 |  
min_delay_step2 | - | 40 |  
max_delay_step2 | - | 80 |  
power_step2 | - | L |  
power_step3 | - | L |  
duration_step1 | - | 69 |  
duration_step2 | - | 662 |  
duration_step3 | - | 365 |  

@jdpye could you help me with this please?

**Comment by jdpye** [comment]
Hi Lien, happy to help if I can, though it seems to me you've got things well in hand? For the purposes of figuring out how to map tags to detection data, your first table is definitely sufficient. 

I did indeed mean we should capture tag programming properties as EMoF, and agree that the tag programming should be a property of the tag, not a detection property. The information you're capturing there in the second table should be enough to give consumers of the data an idea of how often to expect pings from the transmitter attached to the animal. 

Sorry to confuse by talking about acceleration unbidden, I was reading through all the column headers in the transmitter table at the top of this ticket and got ahead of the question (that wasn't asked!). 

I was wondering, is there a lookup associated with manufacturer_fk ? What other issues are outstanding?

**Comment by jreubens** [comment]
@LienReyserhove thelma-converted-code indeed only has NAs for this dataset, as we don't have thelma tags (so far). Thus currently no need to include. But this might change in future datasets..

**Comment by LienReyserhove** [comment]
Ok, this is a summary of the terms to integrate based on the previous discussion:

term | example
--- | ---
tag_full_id | A69-1105-100	
serial_number | 1249187
type | Acoustic
model | V13P-1x	
sensor_type | P
acoustic_tag_type | animal
manufacturer_fk | 1
status | active
estimated_lifetime | 301
frequency | 069k
min_delay | 17
max_delay | 33
power | L
duration_step1 | 69
min_delay_step2 | 40
max_delay_step2 | 80
power_step2 | L
duration_step2 | 662
power_step3 | L
duration_step3 | 365
thelma_converted_code | NA

@jdpye yes there's a look-up associated with `manufacturer_fk`, I will ask for this information and I will integrate it.
