### ISSUE TITLE
Release date before capture date

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#40]
For some animals, the date of release is before the date of capture.
For the following cases, no time has been provided (didn't check them all):

|projectname        | id_pk|utc_release_date_time |catched_date_time   |**utc_release_date_time_new** |
|:------------------|-----:|:---------------------|:-------------------|:---------------------------|
|2012 Leopoldkanaal |   438|2012-07-20 00:00:00   |2012-07-20 15:20:33 |**2012-07-20 15:50:33**       |
|2012 Leopoldkanaal |   439|2012-07-24 00:00:00   |2012-07-24 14:56:09 |**2012-07-24 15:26:09**       |
|2012 Leopoldkanaal |   440|2012-07-24 00:00:00   |2012-07-24 15:29:03 |**2012-07-24 15:59:03**       |
|2012 Leopoldkanaal |   441|2012-07-24 00:00:00   |2012-07-24 16:15:43 |**2012-07-24 16:45:43**       |
|2012 Leopoldkanaal |   442|2012-07-24 00:00:00   |2012-07-24 16:26:30 |**2012-07-24 16:56:30**       |
|2012 Leopoldkanaal |   443|2012-07-19 00:00:00   |2012-07-19 11:36:47 |**2012-07-19 12:06:47**       |
|2012 Leopoldkanaal |   444|2012-07-19 00:00:00   |2012-07-19 14:06:19 |**2012-07-19 14:36:19**       |
|2012 Leopoldkanaal |   445|2012-07-19 00:00:00   |2012-07-19 14:36:30 |**2012-07-19 15:06:30**       |
|2012 Leopoldkanaal |   446|2012-07-20 00:00:00   |2012-07-20 14:19:21 |**2012-07-20 14:49:21**       |
|2012 Leopoldkanaal |   447|2012-07-20 00:00:00   |2012-07-20 14:59:33 |**2012-07-20 15:29:33**       |
|2012 Leopoldkanaal |   448|2012-07-17 00:00:00   |2012-07-17 16:52:19 |**2012-07-17 17:22:19**       |
|2012 Leopoldkanaal |   449|2012-07-18 00:00:00   |2012-07-18 10:52:49 |**2012-07-18 11:22:49**       |
|2012 Leopoldkanaal |   450|2012-07-18 00:00:00   |2012-07-18 11:53:46 |**2012-07-18 12:23:46**       |
|2012 Leopoldkanaal |   451|2012-07-18 00:00:00   |2012-07-18 14:32:49 |**2012-07-18 15:02:49**       |
|2012 Leopoldkanaal |   452|2012-07-19 00:00:00   |2012-07-19 10:43:20 |**2012-07-19 11:13:20**       |
|2012 Leopoldkanaal |   453|2012-07-17 00:00:00   |2012-07-17 13:33:20 |**2012-07-17 14:03:20**       |
|2012 Leopoldkanaal |   454|2012-07-17 00:00:00   |2012-07-17 13:47:50 |**2012-07-17 14:17:50**       |
|2012 Leopoldkanaal |   455|2012-07-17 00:00:00   |2012-07-17 14:01:14 |**2012-07-17 14:31:14**       |
|2012 Leopoldkanaal |   456|2012-07-17 00:00:00   |2012-07-17 16:07:54 |**2012-07-17 16:37:54**       |
|2012 Leopoldkanaal |   457|2012-07-17 00:00:00   |2012-07-17 16:15:52 |**2012-07-17 16:45:52**       |
|2012 Leopoldkanaal |   458|2012-07-06 00:00:00   |2012-07-06 15:56:45 |**2012-07-06 16:26:45**       |
|2012 Leopoldkanaal |   459|2012-07-06 00:00:00   |2012-07-06 16:10:22 |**2012-07-06 16:40:22**       |
|2012 Leopoldkanaal |   460|2012-07-17 00:00:00   |2012-07-17 11:43:37 |**2012-07-17 12:13:37**       |
|2012 Leopoldkanaal |   461|2012-07-17 00:00:00   |2012-07-17 12:11:58 |**2012-07-17 12:41:58**       |
|2012 Leopoldkanaal |   462|2012-07-17 00:00:00   |2012-07-17 11:53:54 |**2012-07-17 12:23:54**       |
|2012 Leopoldkanaal |   463|2012-07-05 00:00:00   |2012-07-05 13:03:49 |**2012-07-05 13:33:49**       |
|2012 Leopoldkanaal |   464|2012-07-06 00:00:00   |2012-07-06 15:25:50 |**2012-07-06 15:55:50**       |
|2012 Leopoldkanaal |   465|2012-07-06 00:00:00   |2012-07-06 15:37:46 |**2012-07-06 16:07:46**       |
|2012 Leopoldkanaal |   466|2012-07-05 00:00:00   |2012-07-05 11:47:11 |**2012-07-05 12:17:11**       |
|2012 Leopoldkanaal |   467|2012-07-05 00:00:00   |2012-07-05 12:53:47 |**2012-07-05 13:23:47**       |
|2012 Leopoldkanaal |   468|2012-07-05 00:00:00   |2012-07-05 11:34:51 |**2012-07-05 12:04:51**       |
|2012 Leopoldkanaal |   469|2012-07-05 00:00:00   |2012-07-05 11:17:40 |**2012-07-05 11:47:40**       |
|2012 Leopoldkanaal |   470|2012-07-05 00:00:00   |2012-07-05 11:02:59 |**2012-07-05 11:32:59**       |
|2012 Leopoldkanaal |   471|2012-07-04 00:00:00   |2012-07-04 12:03:54 |**2012-07-04 12:33:54**       |
|2012 Leopoldkanaal |   472|2012-07-04 00:00:00   |2012-07-04 11:42:00 |**2012-07-04 12:12:00**       |
|2012 Leopoldkanaal |   473|2012-07-03 00:00:00   |2012-07-03 10:38:35 |**2012-07-03 11:08:35**       |
|2012 Leopoldkanaal |   474|2012-07-04 00:00:00   |2012-07-04 10:24:25 |**2012-07-04 10:54:25**       |
|2012 Leopoldkanaal |   475|2012-07-03 00:00:00   |2012-07-03 12:45:00 |**2012-07-03 13:15:00**       |
|2012 Leopoldkanaal |   476|2012-07-03 00:00:00   |2012-07-03 12:31:20 |**2012-07-03 13:01:20**       |
|2012 Leopoldkanaal |   477|2012-07-03 00:00:00   |2012-07-03 11:00:27 |**2012-07-03 11:30:27**       |
|2012 Leopoldkanaal |   478|2011-10-20 00:00:00   |2011-10-20 10:00:00 |**2011-10-20 10:30:00**       |
|2012 Leopoldkanaal |   479|2012-07-03 00:00:00   |2012-07-03 13:01:05 |**2012-07-03 13:31:05**       |
|2012 Leopoldkanaal |   480|2012-07-03 00:00:00   |2012-07-03 12:37:21 |**2012-07-03 13:07:21**       |
|2012 Leopoldkanaal |   481|2012-07-03 00:00:00   |2012-07-03 12:21:21 |**2012-07-03 12:51:21**       |
|2012 Leopoldkanaal |   482|2012-07-03 00:00:00   |2012-07-03 10:51:02 |**2012-07-03 11:21:02**       |
|2012 Leopoldkanaal |   483|2011-12-04 00:00:00   |2011-12-04 10:00:00 |**2011-12-04 10:30:00**       |
|2012 Leopoldkanaal |   484|2012-07-04 00:00:00   |2012-07-04 10:35:18 |**2012-07-04 11:05:18**       |
|2012 Leopoldkanaal |   485|2011-12-04 00:00:00   |2011-12-04 10:00:00 |**2011-12-04 10:30:00**       |
|2012 Leopoldkanaal |   486|2011-10-20 00:00:00   |2011-10-20 10:00:00 |**2011-10-20 10:30:00**       |
|2012 Leopoldkanaal |   487|2011-10-20 00:00:00   |2011-10-20 10:00:00 |**2011-10-20 10:30:00**       |
|2012 Leopoldkanaal |   229|2012-10-16 00:00:00   |2012-10-16 10:39:07 |**2012-10-16 11:09:07**       |
|2012 Leopoldkanaal |   230|2012-10-16 00:00:00   |2012-10-16 10:57:49 |**2012-10-16 11:27:49**       |
|2012 Leopoldkanaal |   231|2012-10-16 00:00:00   |2012-10-16 10:20:00 |**2012-10-16 10:50:00**       |
|2012 Leopoldkanaal |   232|2012-10-16 00:00:00   |2012-10-16 12:50:34 |**2012-10-16 13:20:34**       |
|2012 Leopoldkanaal |   387|2012-08-21 00:00:00   |2012-08-21 10:22:50 |**2012-08-21 10:52:50**       |
|2012 Leopoldkanaal |   388|2012-08-21 00:00:00   |2012-08-21 10:16:00 |**2012-08-21 10:46:00**       |
|2012 Leopoldkanaal |   390|2012-08-14 00:00:00   |2012-08-14 15:49:41 |**2012-08-14 16:19:41**       |
|2012 Leopoldkanaal |   391|2012-08-14 00:00:00   |2012-08-14 15:49:10 |**2012-08-14 16:19:10**       |
|2012 Leopoldkanaal |   392|2012-08-21 00:00:00   |2012-08-21 10:55:23 |**2012-08-21 11:25:23**       |
|2012 Leopoldkanaal |   393|2012-08-21 00:00:00   |2012-08-21 13:57:00 |**2012-08-21 14:27:00**       |
|2012 Leopoldkanaal |   394|2012-12-14 00:00:00   |2012-12-14 13:00:00 |**2012-12-14 13:30:00**       |
|2012 Leopoldkanaal |   395|2012-08-21 00:00:00   |2012-08-21 13:46:47 |**2012-08-21 14:16:47**       |
|2012 Leopoldkanaal |   396|2012-08-21 00:00:00   |2012-08-21 10:47:15 |**2012-08-21 11:17:15**       |
|2012 Leopoldkanaal |   397|2012-08-14 00:00:00   |2012-08-14 15:48:03 |**2012-08-14 16:18:03**       |
|2012 Leopoldkanaal |   398|2012-08-21 00:00:00   |2012-08-21 14:21:39 |**2012-08-21 14:51:39**       |
|2012 Leopoldkanaal |   399|2012-08-22 00:00:00   |2012-08-22 15:11:05 |**2012-08-22 15:41:05**       |
|2012 Leopoldkanaal |   400|2012-08-21 00:00:00   |2012-08-21 14:49:55 |**2012-08-21 15:19:55**       |
|2012 Leopoldkanaal |   401|2012-08-21 00:00:00   |2012-08-21 12:50:32 |**2012-08-21 13:20:32**       |
|2012 Leopoldkanaal |   402|2012-08-21 00:00:00   |2012-08-21 13:30:47 |**2012-08-21 14:00:47**       |
|2012 Leopoldkanaal |   403|2012-08-08 00:00:00   |2012-08-08 15:12:46 |**2012-08-08 15:42:46**       |
|2012 Leopoldkanaal |   404|2012-08-21 00:00:00   |2012-08-21 10:39:07 |**2012-08-21 11:09:07**       |
|2012 Leopoldkanaal |   405|2012-08-22 00:00:00   |2012-08-22 14:54:08 |**2012-08-22 15:24:08**       |
|2012 Leopoldkanaal |   406|2012-08-21 00:00:00   |2012-08-21 13:08:24 |**2012-08-21 13:38:24**       |
|2012 Leopoldkanaal |   407|2012-08-21 00:00:00   |2012-08-21 14:33:32 |**2012-08-21 15:03:32**       |
|2012 Leopoldkanaal |   408|2012-08-08 00:00:00   |2012-08-08 12:32:41 |**2012-08-08 13:02:41**       |
|2012 Leopoldkanaal |   409|2012-08-08 00:00:00   |2012-08-08 13:37:40 |**2012-08-08 14:07:40**       |
|2012 Leopoldkanaal |   410|2012-08-08 00:00:00   |2012-08-08 14:09:39 |**2012-08-08 14:39:39**       |
|2012 Leopoldkanaal |   411|2012-08-08 00:00:00   |2012-08-08 14:54:11 |**2012-08-08 15:24:11**       |
|2012 Leopoldkanaal |   412|2012-08-21 00:00:00   |2012-08-21 11:05:52 |**2012-08-21 11:35:52**       |
|2012 Leopoldkanaal |   413|2012-08-09 00:00:00   |2012-08-09 10:16:56 |**2012-08-09 10:46:56**       |
|2012 Leopoldkanaal |   414|2012-08-09 00:00:00   |2012-08-09 10:48:19 |**2012-08-09 11:18:19**       |
|2012 Leopoldkanaal |   415|2012-08-09 00:00:00   |2012-08-09 11:13:55 |**2012-08-09 11:43:55**       |
|2012 Leopoldkanaal |   416|2012-08-09 00:00:00   |2012-08-09 11:22:20 |**2012-08-09 11:52:20**       |
|2012 Leopoldkanaal |   417|2012-08-08 00:00:00   |2012-08-08 12:05:39 |**2012-08-08 12:35:39**       |
|2012 Leopoldkanaal |   418|2012-10-08 00:00:00   |2012-10-08 10:40:38 |**2012-10-08 11:10:38**       |
|2012 Leopoldkanaal |   419|2012-10-05 00:00:00   |2012-10-05 12:01:21 |**2012-10-05 12:31:21**       |
|2012 Leopoldkanaal |   420|2012-10-05 00:00:00   |2012-10-05 11:44:05 |**2012-10-05 12:14:05**       |
|2012 Leopoldkanaal |   421|2012-10-05 00:00:00   |2012-10-05 11:16:06 |**2012-10-05 11:46:06**       |
|2012 Leopoldkanaal |   422|2012-10-05 00:00:00   |2012-10-05 10:48:20 |**2012-10-05 11:18:20**       |
|2012 Leopoldkanaal |   423|2012-10-16 00:00:00   |2012-10-16 11:49:46 |**2012-10-16 12:19:46**       |
|2012 Leopoldkanaal |   424|2012-10-16 00:00:00   |2012-10-16 11:20:01 |**2012-10-16 11:50:01**       |
|2012 Leopoldkanaal |   425|2012-10-10 00:00:00   |2012-10-10 10:00:00 |**2012-10-10 10:30:00**       |
|2012 Leopoldkanaal |   426|2012-10-10 00:00:00   |2012-10-10 10:00:00 |**2012-10-10 10:30:00**       |
|2012 Leopoldkanaal |   427|2012-10-10 00:00:00   |2012-10-10 10:00:00 |**2012-10-10 10:30:00**       |
|2012 Leopoldkanaal |   428|2012-10-08 00:00:00   |2012-10-08 13:49:32 |**2012-10-08 14:19:32**       |
|2012 Leopoldkanaal |   429|2012-10-08 00:00:00   |2012-10-08 14:11:27 |**2012-10-08 14:41:27**       |
|2012 Leopoldkanaal |   430|2012-10-08 00:00:00   |2012-10-08 14:30:12 |**2012-10-08 15:00:12**       |
|2012 Leopoldkanaal |   431|2012-10-08 00:00:00   |2012-10-08 14:47:57 |**2012-10-08 15:17:57**       |
|2012 Leopoldkanaal |   432|2012-10-08 00:00:00   |2012-10-08 15:00:11 |**2012-10-08 15:30:11**       |
|2012 Leopoldkanaal |   433|2012-10-08 00:00:00   |2012-10-08 13:34:48 |**2012-10-08 14:04:48**       |
|2012 Leopoldkanaal |   434|2012-10-08 00:00:00   |2012-10-08 13:15:17 |**2012-10-08 13:45:17**       |
|2012 Leopoldkanaal |   435|2012-10-08 00:00:00   |2012-10-08 12:55:04 |**2012-10-08 13:25:04**       |
|2012 Leopoldkanaal |   436|2012-10-08 00:00:00   |2012-10-08 12:00:23 |**2012-10-08 12:30:23**       |
|2012 Leopoldkanaal |   437|2012-10-08 00:00:00   |2012-10-08 10:49:30 |**2012-10-08 11:19:30**       |
|2015 PhD Verhelst  |   638|2015-05-22 00:00:00   |2015-05-22 11:02:59 |**2015-05-22 11:32:59**       |
|2015 PhD Verhelst  |   639|2015-05-22 00:00:00   |2015-05-22 09:15:58 |**2015-05-22 09:45:58**       |
|2015 PhD Verhelst  |   640|2015-05-22 00:00:00   |2015-05-22 09:10:56 |**2015-05-22 09:40:56**       |
|2015 PhD Verhelst  |   642|2015-05-22 00:00:00   |2015-05-22 10:46:50 |**2015-05-22 11:16:50**       |
|2015 PhD Verhelst  |   643|2015-05-22 00:00:00   |2015-05-22 09:39:39 |**2015-05-22 10:09:39**       |
|2015 PhD Verhelst  |   644|2015-05-21 00:00:00   |2015-05-21 12:42:17 |**2015-05-21 13:12:17**       |
|2015 PhD Verhelst  |   646|2015-05-22 00:00:00   |2015-05-22 10:23:23 |**2015-05-22 10:53:23**       |
|2015 PhD Verhelst  |   647|2015-05-22 00:00:00   |2015-05-22 09:58:42 |**2015-05-22 10:28:42**       |
|2015 PhD Verhelst  |   648|2015-05-21 00:00:00   |2015-05-21 12:30:41 |**2015-05-21 13:00:41**       |
|2015 PhD Verhelst  |   613|2015-10-21 00:00:00   |2015-10-21 12:58:20 |**2015-10-21 13:28:20**       |
|2015 PhD Verhelst  |   614|2015-10-21 00:00:00   |2015-10-21 13:46:04 |**2015-10-21 14:16:04**       |
|2015 PhD Verhelst  |   615|2015-10-21 00:00:00   |2015-10-21 14:02:32 |**2015-10-21 14:32:32**       |
|2015 PhD Verhelst  |   616|2015-10-21 00:00:00   |2015-10-21 14:31:44 |**2015-10-21 15:01:44**       |
|2015 PhD Verhelst  |   617|2015-10-22 00:00:00   |2015-10-22 12:58:07 |**2015-10-22 13:28:07**       |
|2015 PhD Verhelst  |   618|2015-10-22 00:00:00   |2015-10-22 13:36:18 |**2015-10-22 14:06:18**       |
|2015 PhD Verhelst  |   612|2015-09-17 00:00:00   |2015-09-17 12:34:59 |**2015-09-17 13:04:59**       |
|2015 PhD Verhelst  |   619|2015-09-18 00:00:00   |2015-09-18 12:11:49 |**2015-09-18 12:41:49**       |
|2015 PhD Verhelst  |   620|2015-09-18 00:00:00   |2015-09-18 12:36:55 |**2015-09-18 13:06:55**       |
|2015 PhD Verhelst  |   380|2015-06-06 00:00:00   |2015-06-06 16:05:38 |**2015-06-06 16:35:38**       |
|2015 PhD Verhelst  |   379|2015-04-17 00:00:00   |2015-04-17 13:28:48 |**2015-04-17 13:58:48**       |
|2015 PhD Verhelst  |   378|2015-04-17 00:00:00   |2015-04-17 12:49:10 |**2015-04-17 13:19:10**       |
|2015 PhD Verhelst  |   381|2015-06-06 00:00:00   |2015-06-06 16:55:07 |**2015-06-06 17:25:07**       |
|2015 PhD Verhelst  |   598|2015-08-18 00:00:00   |2015-08-18 15:20:33 |**2015-08-18 15:50:33**       |
|2015 PhD Verhelst  |   599|2015-08-18 00:00:00   |2015-08-18 14:55:11 |**2015-08-18 15:25:11**       |
|2015 PhD Verhelst  |   600|2015-08-18 00:00:00   |2015-08-18 15:06:37 |**2015-08-18 15:36:37**       |
|2015 PhD Verhelst  |   601|2015-08-19 00:00:00   |2015-08-19 15:53:09 |**2015-08-19 16:23:09**       |
|2015 PhD Verhelst  |   602|2015-08-20 00:00:00   |2015-08-20 15:51:18 |**2015-08-20 16:21:18**       |
|2015 PhD Verhelst  |   603|2015-08-20 00:00:00   |2015-08-20 17:07:09 |**2015-08-20 17:37:09**       |
|2015 PhD Verhelst  |   604|2015-08-20 00:00:00   |2015-08-20 17:29:29 |**2015-08-20 17:59:29**       |
|2015 PhD Verhelst  |   625|2015-08-12 00:00:00   |2015-08-12 14:08:44 |**2015-08-12 14:38:44**       |
|2015 PhD Verhelst  |   595|2015-08-12 00:00:00   |2015-08-12 13:16:18 |**2015-08-12 13:46:18**       |
|2015 PhD Verhelst  |   596|2015-08-12 00:00:00   |2015-08-12 13:21:18 |**2015-08-12 13:51:18**       |
|2015 PhD Verhelst  |   597|2015-08-12 00:00:00   |2015-08-12 13:39:35 |**2015-08-12 14:09:35**       |
|2015 PhD Verhelst  |   605|2015-09-16 00:00:00   |2015-09-16 12:08:53 |**2015-09-16 12:38:53**       |
|2015 PhD Verhelst  |   606|2015-09-16 00:00:00   |2015-09-16 12:12:24 |**2015-09-16 12:42:24**       |
|2015 PhD Verhelst  |   607|2015-09-16 00:00:00   |2015-09-16 12:39:50 |**2015-09-16 13:09:50**       |
|2015 PhD Verhelst  |   608|2015-09-16 00:00:00   |2015-09-16 12:47:53 |**2015-09-16 13:17:53**       |
|2015 PhD Verhelst  |   609|2015-09-16 00:00:00   |2015-09-16 12:58:01 |**2015-09-16 13:28:01**       |
|2015 PhD Verhelst  |   610|2015-09-16 00:00:00   |2015-09-16 13:09:06 |**2015-09-16 13:39:06**       |
|2015 PhD Verhelst  |   611|2015-09-17 00:00:00   |2015-09-17 12:17:22 |**2015-09-17 12:47:22**       |
|2015 PhD Verhelst  |   621|2015-10-20 00:00:00   |2015-10-20 12:13:34 |**2015-10-20 12:43:34**       |
|2015 PhD Verhelst  |   622|2015-10-20 00:00:00   |2015-10-20 12:34:24 |**2015-10-20 13:04:24**       |
|2015 PhD Verhelst  |   623|2015-10-20 00:00:00   |2015-10-20 13:16:23 |**2015-10-20 13:46:23**       |
|2015 PhD Verhelst  |   624|2015-10-20 00:00:00   |2015-10-20 14:16:58 |**2015-10-20 14:46:58**       |

**Comment by jreubens** [comment]
for the animals of Phd Reubens tag and release data should be the same.
The correct value is 2010-10-01 and this has been adapted in the DB.

Other animals are all related to INBO projects

**Comment by jreubens** [comment]
can you assign @PieterjanVerhelst  for this issue

**Comment by PieterjanVerhelst** [comment]
For the fish of `2012 Leopoldkanaal` and `2015 PhD Verhelst` we did not log the release time. I see 2 solutions:
1) we determine the release date & time as the last catch date & time + 30 min (per day off course). This will not deviate substantially from the exact release time. Specifically, all fish are released when the last fish is recovered from the anaesthetic, which takes ca. 30 min.
2) another option is that both release and catch fields have time `00:00:00`. However, than we loose the information about the catching date and time.

I suggest to apply 1).

**Comment by peterdesmet** [comment]
@PieterjanVerhelst sounds good to me.

**Comment by LienReyserhove** [comment]
Fine, I will integrate this accordingly

**Comment by LienReyserhove** [comment]
I updated the overview.
@jreubens I overlooked a few of these release dates, could you also update them please?

@fwaumans could you please update the data from the second table in the database? Values for `utc_release_date_time` for these specific `id_pk` should be replaced by `catched_date_time + 30 minutes` (see table)

**Comment by jreubens** [comment]
done!

**Comment by fwaumans** [comment]
I have updated the `utc_release_date_time`.
