### ISSUE TITLE
Cleanded content for release locations

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#41]
**NOTE: This table is updated with the changes discussed further in this issue**

The current values in `release_location` should be cleaned somewhat before mapping to the DwC term `locality`. I suggest the following actions (see also #34 for cleaning of `capture_location` and #42 for cleaning of `surgery_location`) 

1. Complete missing values for `release_location`, `release_latitude` and `release_longitude`

projectname | id_pk
-- | --
2013 Albertkanaal | 2353
2013 Albertkanaal | 2348
2013 Albertkanaal | 2354
2013 Albertkanaal | 2350
2013 Albertkanaal | 2352
2013 Albertkanaal | 2349
2013 Albertkanaal | 2347
2013 Albertkanaal | 2345
2013 Albertkanaal | 2355
2013 Albertkanaal | 2356
2013 Albertkanaal | 2357
2013 Albertkanaal | 2331
2013 Albertkanaal | 2332
2013 Albertkanaal | 2333
2013 Albertkanaal | 2334
2013 Albertkanaal | 2343
2013 Albertkanaal | 2337
2013 Albertkanaal | 2344
2013 Albertkanaal | 2338
2013 Albertkanaal | 2335
2013 Albertkanaal | 2336
2013 Albertkanaal | 2342
2013 Albertkanaal | 2339
2013 Albertkanaal | 2341
2013 Albertkanaal | 2346
2013 Albertkanaal | 2330
2013 Albertkanaal | 2340
2013 Albertkanaal | 2351
2013 Albertkanaal | 2358

2. **More information requested:**

|release_location                       | records|release_location_clean
|:---------------------------------|---------|------------------------:|
|HH5                    |      86| ?
|M-4-1 (LO)             |      17| ?
|M-4a-1 (RO)            |       2| ?
|M-4 (LO)               |       7| ?

3. Release locations of Genk, Diepenbeek and Hasselt 

(see https://github.com/inbo/etn-occurrences/issues/41#issuecomment-529480105)

For the release locations of Genk and Diepenbeek, the names “Genk”, “Diepenbeek” and “Hasselt” should be changed to: “Upstream shipping lock Genk”/ “Upstream shipping lock Diepenbeek”/ “Upstream shipping lock Hasselt”, respectively.

**Comment by PieterjanVerhelst** [comment]
The eel from my PhD (id_pk = 2160) was released in the Drowned Land of Saeftinghe. I added `VLVS` to the database (Verdronken Land van Saeftinghe).
The other issues are related to the projects Albertkanaal and Dijle, for which @IPauwels can provide the information.

**Comment by jreubens** [comment]
for D5, D6, I agree to have the same naming as for capture_location

**Comment by LienReyserhove** [comment]
@PieterjanVerhelst could you please change `VLVS` to `drowned land of Saeftinghe`?

**Comment by PieterjanVerhelst** [comment]
Offcourse :-). I changed the capture location to `Drowned Land of Saeftinghe - Zone 2.2` and the release location to `Drowned Land of Saeftinghe`

**Comment by LienReyserhove** [comment]
Thanks!
I updated the table.
@fwaumans could you please integrate the suggested changes (just the ones with `OK` next to them`)

**Comment by fwaumans** [comment]
I updated the field `release_location`

**Comment by LienReyserhove** [comment]
Thanks. I updated the table in https://github.com/inbo/etn-occurrences/issues/41#issue-431436207. A few more updates are requested, @fwaumans could could please consider the 3rd and 4th point for futher changes in the database?

The rest is for @IPauwels when she returns.

**Comment by IPauwels** [comment]
Regarding the missing info for 2013 Albertkanaal. We will add or change this info in the database later. But for datapublication, this is the info you need now:

- [ ] Fishes caught at `Hatchery Erezée` are hatched fish that were given a tag in the Hatchery of Erezée. The coordinates of the hatchery are: lat/long: 50.306056 , 5.542595. So these are the coördinates for both the catch and surgery location of fishes of catch location `Hatchery Erezée`.

- [ ] All fish that were caught at Genk, were caught at the same location, but the naming of the location differs. This should all be changed to `Shipping lock Genk` and the accompanying coördinate is: 50.9356423, 5.4970086. So, the following `catch location names` should be changed to `Shipping lock Genk`: `Genk`, `Upstream draining channel Genk`, `sluis Genk`, `shipping lock Genk`.

- [ ] Idem for Diepenbeek: All fish that were caught at Diepenbeek, were caught at the same location, but the naming of the location differs. This should all be changed to `Shipping lock Diepenbeek`, and the accompanying coördinate is: 50.9380396, 5.4373164. So, the following `catch location names` should be changed to `Shipping lock Diepenbeek`: `Diepenbeek`, `Upstream drainage channel Diepenbeek`.

- [ ] Idem for Hasselt: All fish that were caught at Hasselt, were caught at the same location, but the naming of the location differs. This should all be changed to `Shipping lock Hasselt`, and the accompanying coördinate is: 50.9380396, 5.4373164. So, the following `catch location names` should be changed to `Shipping lock Hasselt`: `Hasselt`, `Upstream drainage channel Hasselt`.

- [ ] For the release locations of Genk and Diepenbeek, the names `Genk`, `Diepenbeek` and `Hasselt` should be changed to: `Upstream shipping lock Genk`/`Upstream shipping lock Diepenbeek`/ `Upstream shipping lock Hasselt`, respectively.

**Comment by LienReyserhove** [comment]
@IPauwels thank you for this input. Related to the points where I need to change the capture and/or release locations: do I consider the surgery location to be the same as the capture location?

**Comment by LienReyserhove** [comment]
@IPauwels I would also need the **release latitudes and longitudes** for the following records:

projectname | id_pk
-- | --
2013 Albertkanaal | 2353
2013 Albertkanaal | 2348
2013 Albertkanaal | 2354
2013 Albertkanaal | 2350
2013 Albertkanaal | 2352
2013 Albertkanaal | 2349
2013 Albertkanaal | 2347
2013 Albertkanaal | 2345
2013 Albertkanaal | 2355
2013 Albertkanaal | 2356
2013 Albertkanaal | 2357
2013 Albertkanaal | 2331
2013 Albertkanaal | 2332
2013 Albertkanaal | 2333
2013 Albertkanaal | 2334
2013 Albertkanaal | 2343
2013 Albertkanaal | 2337
2013 Albertkanaal | 2344
2013 Albertkanaal | 2338
2013 Albertkanaal | 2335
2013 Albertkanaal | 2336
2013 Albertkanaal | 2342
2013 Albertkanaal | 2339
2013 Albertkanaal | 2341
2013 Albertkanaal | 2346
2013 Albertkanaal | 2330
2013 Albertkanaal | 2340
2013 Albertkanaal | 2351
2013 Albertkanaal | 2358

**Comment by fwaumans** [comment]
Updated the field  release_location for the 3rd and 4th point

**Comment by IPauwels** [comment]
> > @IPauwels thank you for this input. Related to the points where I need to change the capture and/or release locations: do I consider the surgery location to be the same as the capture location?
> 
> Yes Lien, the release and catch locations can be considered the same.

Sorry! Completely wrong ... I meant: the catch and surgery locations should be considered the same!

**Comment by IPauwels** [comment]
Lien, I have completed the animals in the 2011 Rivierprik project. I added release long/lat, surgery long/lat and location, surgery date. I think this dataset is complete now, except for the fact that I noticed that we are missing detections of animals that were tagged and released in 2011! I asked the project responsible if he can provide me those data.

For the Albertkanaal project, I have not completed the database yet and I cannot find the time to do this now. I will ask this to our field workers during harsh winter conditions, when they work inside. For now, you can complete those data automatically in the database-for-publication by indicating that the release location is the same for the catch location (except for hatched animals, for which I already completed the database).

**Comment by LienReyserhove** [comment]
Ok, thank you for your updates! 
I integrated all the information in the mapping. Later on, we can then change it in the database.
I will keep this issue open to remind us that these changes still need to happen.

**Comment by peterdesmet** [comment]
@IPauwels based on [your comment](https://github.com/inbo/etn-occurrences/issues/41#issuecomment-529480105), the required update would be the table below. I can update the catch and release location (can you provide coordinates for the release location as well?), but I am not planning to update the surgery location = catch location:

catch_location | new_catch_location | catch_lat | catch_long | new_release_location | release_lat | release_long
-- | -- | -- | -- | -- | -- | --
Hatchery Erezée | Hatchery Erezée | 50.306056 | 5.542595 |   |   |  
Genk | Shipping lock Genk | 50.936 | 5.497 | Upstream shipping lock Genk | 50.936 | 5.497
Upstream draining channel Genk | Shipping lock Genk | 50.936 | 5.497 | Upstream shipping lock Genk | 50.936 | 5.497
sluis Genk | Shipping lock Genk | 50.936 | 5.497 | Upstream shipping lock Genk | 50.936 | 5.497
shipping lock Genk | Shipping lock Genk | 50.936 | 5.497 | Upstream shipping lock Genk | 50.936 | 5.497
Diepenbeek | Shipping lock Diepenbeek | 50.938 | 5.437 | Upstream shipping lock Diepenbeek | 50.938 | 5.437
Upstream drainage channel Diepenbeek | Shipping lock Diepenbeek | 50.938 | 5.437 | Upstream shipping lock Diepenbeek | 50.938 | 5.437
Hasselt | Shipping lock Hasselt | 50.941 | 5.374 | Upstream shipping lock Hasselt | 50.941 | 5.374
Upstream drainage channel Hasselt | Shipping lock Hasselt | 50.941 | 5.374 | Upstream shipping lock Hasselt | 50.941 | 5.374

**Comment by peterdesmet** [comment]
All Diepenbeek, Hasselt en Genk capture and release locations/coordinates are now uniform.

```R
get_animals(animal_project_code = "2013_albertkanaal") %>%
	filter(scientific_name == "Anguilla anguilla") %>%
	group_by(scientific_name, aphia_id, capture_location, capture_latitude, capture_longitude, release_location, release_latitude, release_longitude) %>%
	arrange(capture_location, release_location) %>%
	count() %>%
	View()
```
