### ISSUE TITLE
Cleanded content for surgery locations

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#42]
The current values in `surgery_location` should be cleaned somewhat before mapping to the DwC term `locality`. I suggest the following actions (see also #34 for cleaning of `capture_location and #41 for cleaning of `release_location)

1. Give more information for some of the locations

|surgery_location                     |surgery_location_clean
|:----------------------------------------|---------------------|
|tss D5 en D6     | between wind turbine D5 and D6 C-Power
|tussen D5 en D6 | between wind turbine D5 and D6 C-Power
|D5                        |wind turbine D5 C-Power
|D6                         |wind turbine D6 C-Power

**Comment by PieterjanVerhelst** [comment]
I agree. The only thing that should be changed, is naming 'stuw' and 'veerboot' in English: 
`Dijle (weir Mechelen Nekkerspoel)` 
`Zeeschelde (ferry, Kastel)`

**Comment by LienReyserhove** [comment]
@fwaumans could you integrate these changes please?

**Comment by fwaumans** [comment]
`Surgery_location` updated

**Comment by LienReyserhove** [comment]
I updated the table in https://github.com/inbo/etn-occurrences/issues/42#issue-431438185.
Some locations still need updates, @fwaumans could you please integrate them in the database please?

**Comment by fwaumans** [comment]
Surgery_location updated
