### ISSUE TITLE
Complete surgery latitude/longitude

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#43]
In line with the discussion in #33, please complete the missing values for `surgery_latitude` and `surgery_longitude` using the following criteria:

1. Only complete `surgery_latitude` and `surgery_longitude` for records with a value for `date_of_surgery`. When no `date_of_surgery` is provided, leave these fields empty.

2. In most of these cases: `surgery_latitude` = `release_latitude` and `surgery_longitude` = `release_longitude`

3. In two cases (`id_pk` = 458 and `id_pk` = 459) however `surgery_latitude` = `capture_latitude` and `surgery_longitude` = `capture_longitude`:

| id_pk|surgery_location                 | capture_latitude| capture_longitude|
|-----:|:--------------------------------|----------------:|-----------------:|
|   458|LEOPOLDKANAAL (STENENSCHUURBRUG) |         51.26664|          3.661414|
|   459|LEOPOLDKANAAL (STENENSCHUURBRUG) |         51.26664|          3.661414|

**Comment by fwaumans** [comment]
Fields surgery_latitude and surgery_longitude are completed

**Comment by LienReyserhove** [comment]
@fwaumans  I would suggest to extend this issue to all surgery dates and locations, i.e. where `date_of_surgery` is empty, use the following criteria to supplement `date_of_surgery` , `surgery_latitude` and `surger_longitude` information:
- `date_of_surgery` = `utc_release_date_time`
- `surgery_latitude` = `release_latitude`
- `surgery_longitude` = `release_longitude`

**Comment by LienReyserhove** [comment]
This is a copy-paste from the https://github.com/inbo/etn-occurrences/issues/41#issuecomment-529480105 by @IPauwels 

> Fishes caught at ‘Hatchery Erezée’ are hatched fish that were given a tag in the Hatchery of Erezée. The coordinates of the hatchery are: lat/long: 50.306056 , 5.542595. So these are the coördinates for both the catch and surgery location of fishes of catch location ‘Hatchery Erezée’.

**Comment by LienReyserhove** [comment]
To summarize: by solving this issue, 43% of the values for `surgery_latitude` and `surgery_longitude` could be provided. For the remaining empty values, see #47
