### ISSUE TITLE
Fish without length information

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#44]
The following individuals have no length information but do have length_type provided. Can these values be supplied?

For VLIZ:
@jreubens 

|projectname     | id_pk| length|length_type  |
|:---------------|-----:|------:|:------------|
|Homarus         |   251|     NA|total length |
|Homarus         |   252|     NA|total length |
|PhD Jan Reubens |   674|     NA|total length |

For INBO:
@PieterjanVerhelst 

|projectname        |scientific_name   | id_pk| length2|length2_type            |
|:------------------|:-----------------|-----:|-------:|:-----------------------|
|2012 Leopoldkanaal |Anguilla anguilla |   483|      NA|horizontal eye diameter |

**Comment by PieterjanVerhelst** [comment]
For the eel from `2012 Leopoldkanaal`, I removed `length2_type` and `length2_unit` as this was not measured for this particular fish.

**Comment by jreubens** [comment]
For the Homarus there is no length info available. The animals were tagged while diving. I removed the 'length_type' and 'length_unit' for these animals.
id_pk 674 has been updated

**Comment by LienReyserhove** [comment]
Thank you for the adaptations!
