### ISSUE TITLE
Anaesthetic concentration

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#45]
The content of the field `anaesthetic_concentration` looks like this:

|anaesthetic_concentration | records|
|:-------------------------|-------:|
|NA                        |     379|
|0.02 ml/L                 |      80|
|0.2 ml/L                  |      11|
|0.2ml/L                   |       1|
|0.3ml/L                   |     189|

Two options here:
1. Clean up the content by adding space between the value and its unit (which we can use as a separator later to map `measurementValue` and `measurementUnit`)
2. Create two new fileds `anaesthetic_concentration_value` and `anaesthetic_concentration_unit` and assign accordingly.

I prefer option 2 which is in line with other measurement data such as length and weight. This would also imply that we can eliminate one data processing step in the mapping process. I'm not not sure however whether this suggested change is allowed in the database.

**Comment by PieterjanVerhelst** [comment]
Indeed, I agree to apply '2.' as it is in line with the other measurements.

**Comment by LienReyserhove** [comment]
@fwaumans can you integrate these changes in the database please (option 2)

**Comment by fwaumans** [comment]
I have added a space between the value and the unit. Later on, I will split then into two fields.

**Comment by peterdesmet** [comment]
The values in the DB are all ok for the data paper:

anaesthetic_concentration | n
--- | ---
0.025 ml/L | 3
0.02 ml/L | 81
0.10 ml/L | 1
0.15 ml/L | 2
0.1 ml/L | 9
0.2 ml/L | 21
0.3 ml/L | 198
NA | 490

But the field is not split, I think it will stay that way

**Comment by PieterjanVerhelst** [comment]
@peterdesmet a bit too fast I'm afraid. I must have missed this issue, but the concentrations `0.025 ml/L` and `0.02 ml/L` need to be `0.25 ml/L` and `0.2 ml/L` respectively, if these values occur in projects from my phd, specifically `2015_phd_verhelst_eel` and `2015_phd_verhelst_cod`. Apologize for this late notification.

**Comment by peterdesmet** [comment]
Thanks! Now fixed for `2015_phd_verhelst_cod `, still to fix for `2015_phd_verhelst_eel`.

**Comment by peterdesmet** [comment]
Now also fixed in `2015_phd_verhelst_eel`
