### ISSUE TITLE
Post operation holding period

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#46]
In line with #45 

`post_op_holding_period` is provided for (only one!) value in the dataset (within the scope of publication) : `1 hour`.

Three options here:

1. Separate `post_op_holding_period` into is value and unit in the mapping script. 
2. Create two new fields `post_op_holding_period_value` and `post_op_holding_period_unit` in the database
3. Use ISO 8601 format for durations: `T[n]H[n]M[n]S`, with  `[n]` replaced by the value for each time element that follows the [n], `T` the time designator that precedes the time components of the representation, `H` the hour designator that follows the value for the number of hours, etc. To make clear that his is an ISO format I would add `ISO8601:` as a prefix. @peterdesmet is this interpretation correct?

I prefer option 3 here as this is a standardized format. I'm not not sure however whether this suggested change is allowed in the database.

NB: (but outside the scope of the data publication):
This field contains more values when you consider all animal project:
`1'59"`, `6'53"` `3'58"`, `1 hour` and `0.1` This issue is applicable to these values as well.

**Comment by fwaumans** [comment]
Because only 1 value is stored in the `field post_op_holding_period` I would suggest option 1 for now. It is possible to store duration in a special PostgreSQL datatype but than I have to change the database and the applications depending on it. I can't do that in the short term.

**Comment by peterdesmet** [comment]
Note, the field is now called `post_surgery_holding_period` and indeed, only 1 record has a value: `1 hour`
