### ISSUE TITLE
Missing surgery date and locations

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#47]
I'm repeating the comment from a previous issue here (https://github.com/inbo/etn-occurrences/issues/33#issuecomment-481253907) as it is quite important for the mapping process:

> There's still the problem that date_of_surgery is empty for about 57% of the events and surgery_latitude and surgery_longitude are always empty (for the data within the publication scope)

I found out that `surgery_latitude` and `surgery_longitude` can be derived by comparing `surgery_location` with `capture_location` or `release_location`, but there's still no way to figure out whether surgery even occured for the remaining 57% of data with no information whatsoever relating to the surgery event. So my question is:

1. Did 57% of the animals have **no surgery at all**?
2. Did surgery occur but are these records missing from the database?

If 1 is true, then I can just do the mapping for the 43% that did have surgery. In case 2 is true, then I have to do the mapping for all data, but at this points most records will be empty.

**Comment by PieterjanVerhelst** [comment]
All fish had a surgery to be given a tag. The surgery locations is not always exact the catching location. For instance, eels are caught near the shipping lock complex in Merelbeke, but we need to boat to a slibway near the fire department of Merelbeke 3.5 kilometer downstream, to get everything on land and perform the surgery. At sea with anglers, it was sometimes even more complex: a cod was caught at shipping wreck A but while I was operating, they shipped to shipping wreck B were I released the respective fish... I do have this information, so we could implement this for the respective projects (i.e. PhD Verhelst). For the `2015 Dijle` project I know the surgery location as well. Locations for Albertkanaal and Demer @IPauwels can provide the information.

**Comment by LienReyserhove** [comment]
OK for the locations, but we would really need information about the surgery **dates**. How can we retrieve this information, can it be derived from e.g the release date?

**Comment by PieterjanVerhelst** [comment]
The surgery date is the same as the catch date :-).

**Comment by LienReyserhove** [comment]
Is this really always the case? As the surgery locations are not always exact the catching locations (and in some cases the surgery location is equal to the release location, see #33), I can assume that the surgery date is not always equal to the catch date, especially as the date information is supplemented with the time of day.

**Comment by jreubens** [comment]
For all fish we tagged the date is the same! I suppose this is also the case for INBO...

**Comment by PieterjanVerhelst** [comment]
@LienReyershove, surgery date is not always the same as catch date, I was wrong! Salmon smolts for instance were tagged at a hatchery and I think they were kept under observation after tagging to be released some days later. I will check this.

**Comment by IPauwels** [comment]
@LienReyserhove At INBO we also always tagged the fish at the day he was caught. We also release the fishes (almost) always at the same day that we caught and tagged them. We have all catch dates available, I will provide them.

**Comment by IPauwels** [comment]
Regarding the salmon smolts: the catch (hatchery ...) and surgery date are the same, but the release date might differ indeed, as Pieterjan mentioned! We did keep some of the fish under observation before release, also because we did not want to release them all together (5 at a time).

**Comment by LienReyserhove** [comment]
Update: based on the discussions in this issue, I now considered surgery date to be the same as the capture date for all records without surgery date.

Now I still need the **surgery location**.
@PieterjanVerhelst and @IPauwels could you provide this information for all cases where surgery location is **not equal to** the capture location?

Note: these changes still need to be integrated in the database, but I already included them in the Darwin Core mapping.

**Comment by PieterjanVerhelst** [comment]
@LienReyershove eels from '2015 PhD Verhelst' with capture location 'Zeeschelde (ringvaart, Merelbeke)' were tagged at the slibway in Melle with the following coordinates: 51.006930, 3.799597. The other eels from '2015 PhD Verhelst' were tagged at catch location.
Also, all twaite shads (Alosa fallax) were tagged at catch location.

**Note by @LienReyserhove : this information is integrated in the mapping. There's only one empty record for 2015 PhD Verhelst in the database, and this is one for capture_location = Drowned Land of Saeftinghe. For this location, tag location equals catch location**

**Comment by LienReyserhove** [comment]
Update: In #43 , `surgery_latitude` and `surgery_longitude` have been provided for those recods with a `date_of_surgery` provided.  This means that we 'only' need location information (locality, latitude and longitude) for the remaining 57%

**Comment by LienReyserhove** [comment]
Update: This is a copy-paste from the https://github.com/inbo/etn-occurrences/issues/41#issuecomment-529480105 by @IPauwels 

> Fishes caught at ‘Hatchery Erezée’ are hatched fish that were given a tag in the Hatchery of Erezée. The coordinates of the hatchery are: lat/long: 50.306056 , 5.542595. So these are the coördinates for both the catch and surgery location of fishes of catch location ‘Hatchery Erezée’.

**Comment by IPauwels** [comment]
Except for hatched salmon (project Albertkanaal), the surgery location and date are the same as the catch location and date. Do you need more info from me still regarding this issue?

**Comment by peterdesmet** [comment]
I think it is fine to leave the surgery date empty in the database (assumed to be the same as catch date in most cases), it is the case for many projects:

animal_project_code | n
--- | ---
2010_phd_reubens | 41
2011_rivierprik | 31
2012_leopoldkanaal | 104
2015_homarus | 2
2015_phd_verhelst_cod | 70
2015_phd_verhelst_eel | 136

However, 1 record in `2010_phd_reubens` and 38 records in `2015_phd_verhelst_eel` have a surgery date BEFORE the capture data. That would be best corrected: [to-correct.txt](https://github.com/inbo/etn-occurrences/files/5542608/to-correct.txt) @PieterjanVerhelst

**Comment by PieterjanVerhelst** [comment]
@peterdesmet the 38 eels in `2015_phd_verhelst_eel` were tagged (=had surgery) the day of capture. Hence, `capture_date_time` = `surgery_date_time`. 
The cod in the project by @jreubens is probably a date-time issue (1st of October or 10th of January).
Thanks for checking!

**Comment by peterdesmet** [comment]
@PieterjanVerhelst ok if I then also set the time (in addition to the date) for surgery the same as for capture? I notice the release is often half an hour later.

**Comment by jreubens** [comment]
@peterdesmet can you inform me which animal still has that surgery date before capture date? I'll adapt then

**Comment by peterdesmet** [comment]
@jreubens it is animal_id 673 with tag A69-1303-20695, which release_date and surgery_date should be `2010-08-09 13:00` (and not september). It cannot be set via the interface, I'm noting it for Aubri.
