### ISSUE TITLE
Why are catches of the same animal 2 records in the animal table/view?

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#48]
In the animal table, it appears that six individuals (indicated in `individual` here) have two records instead of one. Five of these individuals (10 records, first table) differ mainly in their dates of capture, surgery and release and also differ in their length. For each of these individuals, one record has a date of recapture provided, which suggests that these double records are a consequence of the recapture of the animal. A sixth individual only differs in its length and weight values (second table). 
The consequence of these double records is that `id_pk` can't be used as a unique identifier for an animal as these animals get assigned two identifiers.

individual |projectname        |tag_full_id    |id_pk | length|catched_date_time   |date_of_surgery |utc_release_date_time |recapture_date |
|:-----|-------------|:--------------|:-----|------:|:-------------------|:---------------|:---------------------|:--------------|
1|PhD Jan Reubens    |A69-1303-20695 |674   |   34.6|2011-07-27 00:00:00 |2011-07-27      |2011-07-27 11:30:00   |NA             |
1|PhD Jan Reubens    |A69-1303-20695 |673   |   34.6|2010-08-09 13:00:00 |2010-09-08      |2010-09-08 13:00:00   |2011-05-19     |
2|PhD Jan Reubens    |A69-1303-20698 |678   |   40.0|2011-07-27 00:00:00 |2011-07-27      |2011-07-27 11:30:00   |NA             |
2|PhD Jan Reubens    |A69-1303-20698 |677   |   37.5|2010-10-01 00:00:00 |2010-01-10      |2010-10-01 13:00:00   |2010-12-05     |
3|2012 Leopoldkanaal |A69-1601-29920 |388   |   57.4|2012-08-21 10:16:00 |2012-08-21      |2012-08-21 00:00:00   |2013-09-03     |
3|2013 Albertkanaal  |A69-1601-29920 |389   |   89.0|2014-10-09 00:00:00 |NA              |2014-10-09 00:00:00   |NA             |
4|2012 Leopoldkanaal |A69-1601-29925 |393   |   66.0|2012-08-21 13:57:00 |2012-08-21      |2012-08-21 00:00:00   |2012-12-10     |
4|2012 Leopoldkanaal |A69-1601-29925 |394   |   77.0|2012-12-14 13:00:00 |2012-12-14      |2012-12-14 00:00:00   |NA             |
5|2013 Albertkanaal  |A69-1601-34503 |542   |   32.7|2015-04-22 00:00:00 |NA              |2015-04-22 00:00:00   |2015-04-26     |
5|2013 Albertkanaal  |A69-1601-34503 |543   |   30.4|2015-04-27 00:00:00 |NA              |2015-04-27 00:00:00   |NA             |

individual |projectname       |tag_full_id    |id_pk | length| weight|
|:------|-----------|:--------------|:-----|------:|------:|
6|2013 Albertkanaal |A69-1601-34486 |524   |   28.4|  254.0|
6|2013 Albertkanaal |A69-1601-34486 |525   |   29.6|  329.8|

**Comment by peterdesmet** [comment]
@jreubens @PieterjanVerhelst @fwaumans can you confirm these are:

1. Six animals that were tagged, released, recaptured (row 1) and released again with the same tag (row 2).
2. And not: six animals that were tagged, released, recaptured, tag removed (row 1) and six other animals for which the same tag was reused (row 2)? Does this ever happen?

Note that in case of 1, the animal table does **not contain 1 record per animal** and as a result different `id_pk` can actually refer to the same animal. We'll have to figure out how to solve this, e.g. by populating `animal_id` for every record.

**Comment by jreubens** [comment]
For the animals of PhD Jan Reubens, there has happened a mistake with the tag codes by vemco. And they gave me the same ID codes twice . But they should have a different serialnumber!
Thus here it are different animals, having a different tag (but with the same ID).
Some of these animals were recaptured by fishermen, but the tag was not reused in another animal...

**Comment by PieterjanVerhelst** [comment]
For the two eels `A69-1601-29920` and `A69-1601-29925` the tags were retrieved and put in another eel.
For the two salmons `A69-1601-34503` and `A69-1601-34486` I will need to ask the involved people.

**Comment by peterdesmet** [comment]
@jreubens since those are different tags, would it be an option to name one of them `A69-1303-20695a` in the DB?

**Comment by jreubens** [comment]
I don't think that is a good idea, as this is linked to the IDs recognized on the receiver. THus iID a or b would never have a match.

**Comment by LienReyserhove** [comment]
@jreubens For the tag data related to `PhD Jan Reubens`
I inspected the tag information related to `tag_full_id` in the tag overview.
- I found two records for `A69-1303-20695` and two records for `A69-1303-20698` in the tag overview, which aligns with the duplicated use of `tag_full_id` in the animal overview. 
- However, within one value for `tag_full_id`, I expected to find a different serial number between the records. This was not the case, the serial numbers were identical. Moreover, I found no difference at all in the provided information. @jreubens should the serial numbers be corrected in the database?

**Comment by jreubens** [comment]
No, this is not possible.
At that time, Vemco made a mistake, there is nothing we can change about this now.
Distinction between animals can only be made based on timing of detection. These were 2 different studies and detections that fall before deployment of second animal are all linked to the first animal. All detection after are all linked to second animal. Is suppose we can't change anything anymore on DB level, however in the framework of the datapaper I'm wondering whether we can do a en b (as Peter suggested) but thus not on DB level

**Comment by LienReyserhove** [comment]
In my opinion I think it's better if we just keep it this way and not use the a and b level. I would try to keep a match between the datapaper and the DB, especially as this only concerns two serial numbers.
