### ISSUE TITLE
Empty values for sensor type

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#50]
Values for the field `tag_sensor_type` are:

tag_sensor_type | number of records
--- | --- 
P | 10
A | 10
NA | 652

This means that for 97% of the records, no sensor type is provided. @PieterjanVerhelst , @jreubens  and @IPauwels can we complete this information?
These empty records occur for the following projects x tag model combinations:

|projectcode        |model         | records|
|:------------------|:-------------|-------:|
|2011_rivierprik    |V7-4x         |      32|
|2011_rivierprik    |V8-4x         |       7|
|2012_leopoldkanaal |V13-1x        |     103|
|2012_leopoldkanaal |V7-4x         |       4|
|2013_albertkanaal  |V13-1x        |     131|
|2013_albertkanaal  |V7-2x         |     114|
|2013_albertkanaal  |V7-4x         |      25|
|2013_albertkanaal  |V9-2x         |      11|
|2014_demer         |V13-1x        |      13|
|2014_demer         |V7-4x         |       3|
|2015_dijle         |V13-1x        |       3|
|2015_dijle         |V7-4x         |      23|
|2015_phd_verhelst  |V13-1x        |      96|
|2015_phd_verhelst  |V13-1x-069k-1 |      40|
|homarus            |V13-1x        |       2|
|phd_reubens        |V9-1x         |      45|

**Comment by PieterjanVerhelst** [comment]
@LienReyershove the majority of the transmitters indeed do not have a sensor. Can you give an overview of the tags which do have a sensor?
Also, model `V13-1x-069k-1` should be `V13-1x`.

**Comment by LienReyserhove** [comment]
Sure, these are the tags which do have a sensor:

|projectcode       |tag_full_id   |sensor_type |
|:-----------------|:-------------|:-----------|
|2013_albertkanaal |A69-1105-100  |P           |
|2013_albertkanaal |A69-1105-101  |P           |
|2013_albertkanaal |A69-1105-103  |P           |
|2013_albertkanaal |A69-1105-102  |P           |
|2013_albertkanaal |A69-1105-104  |P           |
|2013_albertkanaal |A69-1105-105  |P           |
|2013_albertkanaal |A69-1105-106  |P           |
|2013_albertkanaal |A69-1105-107  |P           |
|2013_albertkanaal |A69-1105-108  |P           |
|2013_albertkanaal |A69-1105-109  |P           |
|2013_albertkanaal |A69-9006-1834 |A           |
|2013_albertkanaal |A69-9006-1836 |A           |
|2013_albertkanaal |A69-9006-1838 |A           |
|2013_albertkanaal |A69-9006-1840 |A           |
|2013_albertkanaal |A69-9006-1842 |A           |
|2013_albertkanaal |A69-9006-1844 |A           |
|2013_albertkanaal |A69-9006-1846 |A           |
|2013_albertkanaal |A69-9006-1848 |A           |
|2013_albertkanaal |A69-9006-1850 |A           |
|2013_albertkanaal |A69-9006-1852 |A           |

I changed `V13-1x-069k-1` to `V13-1x` in the database
