### ISSUE TITLE
Tag status - difference between active and available?

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#51]
Could I get more information relating to the field `tag_status`? Now this status is specified as `ACTIVE`, `AVAILABLE` and `ENDED`. There's no explanation in the field defenitions. 
Although the content is quite intuitive, I don't really grab the difference between `active` and `available`. And does `ended` imply that the tag no longer transmits a signal?

**Comment by PieterjanVerhelst** [comment]
`ACTIVE`: a transmitter is implanted in a fish and active in the environment
`ENDED`: the battery has dropped dead from a tag
`AVAILABLE`: a transmitter is 'on the shelf' and available for use

**Comment by LienReyserhove** [comment]
@fwaumans could you please changes these values to lowercase letters?
`active`, `ended` and `available`

**Comment by fwaumans** [comment]
done
