### ISSUE TITLE
Drop dead date before deployment date

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#53]
In `vliz.deployments_view`, 39 receivers have `drop_dead_date` before `deployment_date_time`.
The term `drop_dead_date` is not present in the [field definitions](https://docs.google.com/spreadsheets/d/1XVmoxrzxoBGqC7AYBjTgzUAer0w04D6iiCJW2TW41SU/edit#gid=0), which is a file I generated containing all field definitions dowloaded from the [LifeWatch ETN page](http://www.lifewatch.be/etn/).
Might `drop_dead_date` be equal to `RCV_BATTERY_END_DATE` in the glossary?

> RCV_BATTERY_END_DATE: Estimated date at which receiver will stop recording. This date is calculated automatically from (Deployments/Battery install date) and (Receivers/Expected battery life).

If this is the case, I assume it is plausible that `drop_dead_date` falls before `deployment_date_time`?

**Comment by fwaumans** [comment]
@jreubens : Can you give an explanation for this?

**Comment by jreubens** [comment]
@LienReyserhove can you give me an overview of this 39 deployments?
I'll look into the details then...

**Comment by jreubens** [comment]
drop_dead_date is this a field on DB level or in the webapp? I don't see that field on webapp level...

**Comment by LienReyserhove** [comment]
This is a field on DB level, I retrieved the field in the `vliz.deployments_view` table

**Comment by jreubens** [comment]
@fwaumans, @LienReyserhove can one of you give me the detailed list of deployments where there is an issue. Than I can investigate

**Comment by LienReyserhove** [comment]
@jreubens here the overview of the deployments for which `drop_dead_time` falls before `deploy_date_time` with their primary key. Does this information suffice?

project code |receiver | id_pk | drop_dead_time | deploy_date_time
--- |--- | --- |--- | ---
albert	| VR2W-126195	|1819	|2015-12-22 00:00:00	|2016-01-13 00:00:00
albert	| VR2W-122328	|3298	|2016-09-29 00:00:00	|2016-12-14 00:00:00
albert	| VR2W-122326	|1401	|2015-07-01 00:00:00	|2015-12-05 00:00:00
albert	| VR2W-122366	|3306	|2016-09-29 00:00:00	|2016-11-29 00:00:00
albert	| VR2W-122354	|1476	|2015-11-01 00:00:00	|2016-01-28 00:00:00
albert	| VR2W-124060	|2944	|2016-09-29 00:00:00	|2016-10-10 00:00:00
albert	| VR2Tx-480876	|4454	|2018-10-31 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-122354	|4455	|2018-10-31 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127025	|4490	|2018-10-31 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127024	|4489	|2018-10-31 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127028	|4492	|2018-10-27 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127031	|4493	|2018-10-31 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127033	|4494	|2018-10-27 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127032	|4495	|2018-10-31 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127029	|4491	|2018-10-31 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127023	|4456	|2018-10-26 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-127022	|4457	|2018-10-27 00:00:00	|2018-11-08 00:00:00
albert	| VR2W-126196	|4840	|2018-10-25 00:00:00	|2019-04-08 00:00:00
albert	| VR2W-126196	|4845	|2018-10-25 00:00:00	|2019-04-08 00:00:00
albert	| VR2W-126194	|4856	|2018-10-25 00:00:00	|2019-04-08 00:00:00
albert	| VR2W-126197	|1823	|2015-12-22 00:00:00	|2016-01-13 00:00:00
albert	| VR2W-126194	|1817	|2015-12-22 00:00:00	|2016-01-13 00:00:00
albert	| VR2W-126198	|1825	|2015-12-22 00:00:00	|2016-01-13 00:00:00
albert	| VR2W-126196	|1821	|2015-12-22 00:00:00	|2016-01-13 00:00:00
albert	| VR2W-126199	|1827	|2015-12-22 00:00:00	|2016-01-13 00:00:00
albert	| VR2W-126200	|1829	|2015-12-22 00:00:00	|2016-01-13 00:00:00
albert	| VR2W-122326	|1744	|2015-07-01 00:00:00	|2016-01-12 00:00:00
albert	| VR2W-122319	|2148	|2016-01-11 23:00:00	|2016-01-12 00:00:00
albert	| VR2W-122321	|1937	|2016-01-11 23:00:00	|2016-01-12 00:00:00
albert	| VR2W-122331	|1934	|2016-01-11 23:00:00	|2016-01-12 00:00:00
bpns |	VR2W-129570 | 3518	| 2018-02-28 00:00:00 |	2018-03-14 00:00:00
bpns |	VR2W-123823 | 2497	| 2016-09-26 00:00:00 |	2016-12-14 00:00:00
bpns |	VR2C-450136 | 1690	| 2015-04-21 00:00:00 |	2015-08-13 00:00:00
bpns |	VR2C-450136 | 1392	| 2015-04-21 00:00:00 |	2015-06-25 00:00:00
bpns |	VR2W-127729 | 4864	| 2019-01-28 00:00:00 |	2019-04-17 00:00:00
bpns |	VR2W-127729 | 6058	| 2019-01-28 00:00:00 |	2019-08-26 00:00:00
bpns |	VR2W-130998 | 5999	| 2019-02-25 00:00:00 |	2019-08-26 00:00:00
bpns |	VR2W-129563 | 3517	| 2017-05-13 00:00:00 |	2018-03-14 00:00:00
maas |	VR2W-122155 | 3295	| 2016-09-29 00:00:00 |	2016-11-29 00:00:00
maas |	VR2W-122332 | 3300	| 2016-09-29 00:00:00 |	2016-12-08 00:00:00
maas |	VR2W-122364 | 3302	| 2016-10-15 00:00:00 |	2016-11-29 00:00:00
maas |	VR2W-122365 | 3304	| 2016-09-29 00:00:00 |	2016-12-14 00:00:00
maas |	VR2W-122324 | 2192	| 2015-12-09 00:00:00 |	2016-06-09 00:00:00
maas |	VR2W-124066 | 1507	| 2016-06-09 00:00:00 |	2016-12-12 00:00:00
maas |	VR2W-124078 | 3355	| 2016-06-09 00:00:00 |	2016-12-12 00:00:00
ws2 | VR2W-122329 |	3838 |	2017-12-22 00:00:00	| 2018-06-28 17:00:00
ws2 | VR2W-122368 |	1391 |	2013-12-01 00:00:00	| 2014-01-07 00:00:00
ws2 | VR2W-120884 |	2226 |	2016-07-30 00:00:00	| 2016-09-22 00:00:00
ws2 | VR2W-120887 |	2539 |	2016-12-22 00:00:00	| 2017-02-15 00:00:00

**Comment by peterdesmet** [comment]
`drop_dead_time` = `battery_estimated_end_date`. The table above (with estimated end date before deploy date) can be reproduced with:

```R
get_deployments(open_only = FALSE) %>%
  filter(battery_estimated_end_date < deploy_date_time) %>%
  select(network_project_code, receiver_id, pk, battery_estimated_end_date, deploy_date_time)
```

I think this is only a minor quality issue. Closing.
