### ISSUE TITLE
Remove units from bottom_depth

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#58]
In the `vliz.deployments_view` table, some receiver deployments have a `bottom_depth` with a unit attached to it (`m`). Ideally, these units should be removed:

receiver | id_pk | bottom_depth | projectcode 
-- | -- | -- | -- 
VR2AR-545718 | 4772 | 12 m | bpns 
VR2AR-546900 | 4771 | 12 m | bpns

**Comment by fwaumans** [comment]
I have update the field bottom_depth for these values.
