### ISSUE TITLE
Comments: has_weight:, is_moored:, deploy_number:

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#59]
In `vliz.deployments_view`, the column `comments` often contains the following information:

- `has_weight:, is_moored:, deploy_number:`
- `has_weight:, is_moored:, deploy_number:1`
- `, has_weight:TRUE, is_moored:TRUE, deploy_number:1`

etc.

How do I interpret this information:
- if `has_weight` and/or `is_moored` has no value provided (i.e. is not TRUE), this should considered be as FALSE and thus for that specific record, no weight and/or mooring information is available?
- what about the `deploy_number`?

`

**Comment by PieterjanVerhelst** [comment]
The `has_weight` is a field where we can fill in if a receiver, upon last visit & download, had a mooring weight or not. When the field is not filled in, it is interpreted as `TRUE`. The `is_moored` I am not sure, but I would think it simply means the receiver is moored. However, since this is always the case for an open deployment, I consider this info redundant.
The `deploy_number` is the number of times a receiver has been deployed. I don't think we use this field anymore.

@jreubens any thoughts on this?

**Comment by jreubens** [comment]
I agree with @PieterjanVerhelst is_moored and deploy_number are redundant info in the current workflow. has_weight should be interpreted as Pieterjan mentioned

**Comment by peterdesmet** [comment]
@PieterjanVerhelst should this deployment `comment` be left as is or cleaned up?

**Comment by PieterjanVerhelst** [comment]
@peterdesmet I would clean it up and remove `is_moored` and `deploy_number`.

**Comment by peterdesmet** [comment]
@PieterjanVerhelst so values should be corrected like this?

original | new
--- | ---
, has_weight:, is_moored:, deploy_number:1 Niet alle data is even correct ingevuld. GPS coordinaten en plaatsingsdatum zijn bij benadering ingevuld bij gebrek aan correcte data | has_weight:, Niet alle data is even correct ingevuld. GPS coordinaten en plaatsingsdatum zijn bij benadering ingevuld bij gebrek aan correcte data
, has_weight:, is_moored:, deploy_number:1 | has_weight:
, has_weight:, is_moored:TRUE, deploy_number:1 | has_weight:

**Comment by PieterjanVerhelst** [comment]
@peterdesmet correct

**Comment by peterdesmet** [comment]
@PieterjanVerhelst I notice that `has_weight:FALSE` does not occur. Should we assume it is false if it is not in the comments? I just wonder what the use of `has_weight:(TRUE)` is, can't we remove it completely?


network_project_code | comments with has_weight | comments without has_weight | no comments
--- | --- | --- | ---
2017_Fremur |  |  | 36
albert | 98 | 18 | 331
Ars |  |  | 21
bovenschelde | 16 | 2 | 89
bpns | 43 | 42 | 263
cpodnetwork |  | 9 | 49
demer | 39 |  | 9
dijle | 6 | 7 | 50
leopold | 61 |  | 7
maas | 22 | 1 | 60
pc4c |  | 24 | 43
saeftinghe |  | 6 | 10
SPAWNSEIS |  |  | 85
testvr2ar |  |  | 1
thornton |  |  | 28
ws1 | 19 | 21 | 124
ws2 | 41 | 8 | 247
ws3 | 6 | 2 | 58
zeeschelde | 18 | 8 | 273

**Comment by PieterjanVerhelst** [comment]
@peterdesmet I think we can remove it. We kept record for this info that if we downloaded data from a receiver in the field and we noticed it's mooring weight was lost, we had to take a new one with us for the next data-download round. Obviously, this info becomes redundant in the next deployment.

**Comment by peterdesmet** [comment]
So, remove `, has_weight:[x], is_moored:[x], deploy_number:[x]` for all?

**Comment by PieterjanVerhelst** [comment]
yes

**Comment by peterdesmet** [comment]
All cleaned up, except for:

BPNS `VR2W-110781`: 1 deployment is mobile (on ship) and thus has no mandatory coordinates, for second deployment (tripode bij reefballs Belwind), I set mandatory station_name to `?` I think it is fine to leave it like that.

Some deployments for demer, which @IPauwels will look up.

**Comment by peterdesmet** [comment]
Now resolved in 2014_demer
