### ISSUE TITLE
Clean deployment locations

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#60]
The deployment locations from `vliz.deployments_view` (in `location_name` and `location_description`) need some severe formatting, cleaning and reviewing. As it concerns more than 400 locations, I exported the data and made a Google Spreadsheet [verify deployment locations](https://docs.google.com/spreadsheets/d/1pNYC_Vrjn9zdwRUUUM2yyL9OOMKKjlvGkGK2PC5emJg/edit?usp=sharing) to work more efficiently. 

Concretely, the following steps are required:
- Inspect and clean `location_name` in `location_name_clean`
- Inspect and clean `location_description` in `location_description_clean`
- If both fields have been inspected and cleaned: mark this as `OK` in the respective field.

This will automatically generate a value for `location_new`, which will be used in the mapping and can later be integrated in the database.

@IPauwels, @PieterjanVerhelst and @jreubens I will make a first attempt to clean the data and I will ping you later to check whether or not you agree with the suggested corrections.

**Comment by PieterjanVerhelst** [comment]
I agree with `location_name`. However, `Location_description` is merely meant as a description to find our receivers back in the field. I don't think it is of any value for external users. So before with processing this field, is it actually necessary?
@LienReyserhove, @jreubens, @IPauwels any thoughts on this?

**Comment by jreubens** [comment]
I agree with @PieterjanVerhelst Location_description doesn't have any value of externals. tHis field should not be used in the datapaper

**Comment by PieterjanVerhelst** [comment]
I also dug a bit deeper on `location_name` and this is often a station name, which comes in another field. When it is not a station name, for example `Diepenbeek SA`, it is meaningless to external users, to my opinion. So `location_name` is probably redundant as well. To my opinion, the station name together with the lats and longs suffices for external users (if one of those locations is in Diepenbeek or Dendermonde doesn't add much value). 
The only useful situation I can think of, is when the receiver is located at a specific structure which can impact detectability, like a shipping lock.

**Comment by LienReyserhove** [comment]
I agree that locality information can be reduced to the name of the station (contained in `station_name`). If we combine it with the coordinate information that would suffice for the external user. However, I would also include `location_name` and `location_description` information in the `eventRemarks` field to include as much information as possible in the published dataset.

Two remarks:

- I do wonder whether the abbreviations in `station_name` can be extended to their full description? For me, and by extension for the external user, these abbreviations are quite meaningless. 

- We could also add the town/city information between brackets in the locality field. For example: `station ak-43 (Dessel-Schoten)`, but this requires an extra cleaning step. 

**Note: I updated the gsheets table as we decided to select all deployments information from specific network projects, rather then selecting on specific receivers**

**Comment by PieterjanVerhelst** [comment]
@LienReyershove I would leave the `station_name` as they are. They are indeed often meaningless, simply because this is inherent to the station. For instance the names/numbers of the marine buoys, used in the station names at sea and the Westerschelde.
Instead, we could use `location_name` to mention the town or city, but what with receivers at sea, westerschelde or saeftinghe for instance? I just think that cleaning up the location name will require a lot of effort, without it paying back since it is not that much of an added value for external users (is 'Dessel-Schoten' meaningfull for an American scientiest, if he/she has the coordinates of the station location).

**Comment by LienReyserhove** [comment]
@PieterjanVerhelst OK, I agree that this will be too much effort, the longitude and latitude information is more informative here. I will restrict the locality information to `station_name`. 
Will leave this issue open for a few more days, if I don't get any response I assume that all others agree with this decision (consider this as a silent vote :-) )

**Comment by jreubens** [comment]
I agree with @PieterjanVerhelst
