### ISSUE TITLE
Deviating and lacking values for recover latitude and longitude

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#61]
**Note: the table was updated based on the discussion in this issue**

The values for the recover latitude (`recover_lat` in `vliz.deployments_view`) and recover longitude (`recover_long` in the same table) of some of the receivers are deviating from the expected values. Additionally, for about 55% of the deployments, no recover latitude or longitude is provided (while only 6% has no recover date). Could you please provide the correct information in the database?

1. `recover_lat` and `recover_long` are zero and thus refer to the crossing point of the equator with the central meridian for the following records (remark that most have a `recover_date_time` thus should be recovered somewhere). Those should be supplemented with the correct coordinates:

projectname| id_pk |recover_date_time
--- | ---   | ---    
Albertkanaal|  2430 |       2017-10-24
Albertkanaal|  3256 |       2018-10-23
Albertkanaal|  2781 |       2016-02-12
Albertkanaal|  4438 |       2019-04-03
Albertkanaal|  2129 |       2016-10-11
Albertkanaal|  4453 |             <NA>
Albertkanaal|  3312 |       2018-10-22
Albertkanaal|  2805 |       2016-10-14
Albertkanaal|  2694 |       2017-10-31
Albertkanaal|  2804 |       2016-02-11
Albertkanaal|  2803 |       2015-08-03
Albertkanaal|  2802 |       2015-05-20
Albertkanaal|  1544 |       2015-03-19
Albertkanaal|  2434 |       2017-06-23
Albertkanaal|  4441 |       2019-04-03
Albertkanaal|  2696 |       2017-10-24
Albertkanaal|  1716 |       2016-01-07
Albertkanaal|  2436 |       2017-06-19
Albertkanaal|  3258 |       2018-10-23
Albertkanaal|  1717 |       2016-10-11
Dijle|  3282 |       2016-06-01
Dijle|  3254 |       2016-06-01
Leopoldkanaal|  2778 |       2014-06-10
Leopoldkanaal|  1332 |       2015-11-18
Leopoldkanaal|  1415 |       2015-01-29
Leopoldkanaal|  2127 |       2015-11-18
Leopoldkanaal|  2791 |       2014-10-30
Leopoldkanaal|  2792 |       2015-11-17
Leopoldkanaal|  2793 |       2014-06-10
Leopoldkanaal|  2794 |       2015-01-12
Leopoldkanaal|  1954 |       2016-01-18
Leopoldkanaal|  1603 |       2015-11-18
Leopoldkanaal|  2795 |       2015-04-02
Leopoldkanaal|  1420 |       2014-06-10
Leopoldkanaal|  2797 |       2015-01-29
Leopoldkanaal|  1338 |       2015-11-18
Leopoldkanaal|  2799 |       2014-06-10
Leopoldkanaal|  2800 |       2015-01-29
Leopoldkanaal|  1341 |       2015-11-18
Leopoldkanaal|  2807 |       2015-11-16
Leopoldkanaal|  2806 |       2014-06-10
Westerschelde 1|  2527 |       2017-11-16
Westerschelde 1|  2207 |       2017-02-14
Westerschelde 1|  2024 |       2016-09-21
Westerschelde 2|  2134 |       2015-01-22
Westerschelde 2|  1525 |       2014-10-19
Westerschelde 2|  2135 |       2015-04-15
Zeeschelde|  2256 |       2016-10-11
Noordzeekanaal 2017-2018|  3202 |       2018-03-23

**Comment by jreubens** [comment]
Recover lat or long is normally only provided when it deviates from it original deploy lat/long.
thus in most occassions this won' be filled in.
For the mistakes in  2.  and 3. I updated the info.

**Comment by PieterjanVerhelst** [comment]
Following @jreubens his comment, `1.` is now redunant?

**Comment by LienReyserhove** [comment]
I would prefer that this information is provided in the ETN database, but for the mapping process to Darwin Core, this is OK. I will leave this issue open and provide the deploy lat/long for these specific recovery data. @fwaumans could you integrate these in the database?

**Comment by fwaumans** [comment]
What should I do? Completing the recover lat/long with deploy lat/long when recover lat/long is empty? Tricky,  because we can't make a distinction between recover lat/long that is not completed and a recover lat/long that is the same as a deploy lat/long.

**Comment by PieterjanVerhelst** [comment]
The recover lat/long mainly (only?) differs for receivers that are moored with tripods, I think. These are only a handfull of specific acoustic release receivers (VRAr). Perhaps we can use that as a filter?
@jreubens, or were recover lat/longs also used for some receivers attached to a marine buoy that when adrift?

**Comment by jreubens** [comment]
I would leave it empty when it is empty. It is a non-compulsary field, thus up to the scientiest to provide the information

**Comment by LienReyserhove** [comment]
After this discussion, I agree with @fwaumans and @jreubens to leave the field empty when no recover latitude or longitude is provided as it is difficult to know whether the information is just lacking or whether the recover coordinates equal the deployment coordinates. I would not deduct this information.

What **should** be corrected are the recovery coordinates of the receivers listed in the table at the beginning of this issue. The coordinates refer to the crossing point of the equator with the central meridian (0, 0) and are wrong.

**Comment by jreubens** [comment]
I'll do the update for Noordzeekanaal and Westerschelde. @IPauwels can you do that for the INBO projects

**Comment by peterdesmet** [comment]
This is now corrected in the database and no `recover_latitude`/`recover_longitude` = 0 for our projects. In fact, only one project has still 0 values: `OTN-Tosenfjorden`
