### ISSUE TITLE
latitude and longitude information in detections table

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#62]
In the `vliz.detections_view` table, I can see several fields with latitude and longitude information:
- `latitude`
- `longitude`
- `deployment_lat`
- `deployment_long`

I have two questions:

- (sorry for this perhaps naive question, I have some problems interpreting the data). Can a **detection** be linked to a specific latitude/longitude? By this I mean: does the database include lat/long information for a specific transmitter at a specific time point (or the biological interpretation, I guess, would be the exact **position of the fish**, rather then the receiver, at that time point)? As I can see it now, the database has no such information, only the date and time information for that specific detection record is given. What I can find is lat/long information for the specific receivers, which I link to the **deployments** rather then to the detections: i.e. the position of the receiver will not change during the whole deployment period. 

- What it the difference between `latitude` and `deployment_lat` (same for longitude) in the specific table? `latitude` is often empty or 0 (which is incorrect), `deployment_lat` is almost always provided. `latitude` and `longitude` are not always the same however.

**Comment by fwaumans** [comment]
In the `vliz.detection_view`   is
`latitude` and `longitude` coming from a detection record
`deployment_lat` and `deployment_lon` coming from a deployment record
@jreubens : can you answer point 1?

**Comment by PieterjanVerhelst** [comment]
The lats and longs from the detections are indeed the lats and longs from the receiver who detected the tagged fish. A transmitter therefore does not have an exact position, but the position of the receiver.
However, it is possible in specific receiver setups to calculate the exact transmitter position through, for instance, triangulation. @jreubens  is this type of data already included in the database?

**Comment by LienReyserhove** [comment]
If I understand it correctly, then:
- `deployment_lat` = `latitude`
- `deployment_long` = `longitude`

as both are linked to the receiver.

However, this is not always the case, for many records, `deployment_lat` does not equal `latitude` (same for longitude). Any explanation?

**Comment by jreubens** [comment]
Deploy_lat and deploy_long should indeed be similar to lat and long.
However. lat en long are fields a scientist can fill in on the receiver while initializing it. Often mistakes occur there. 
Thus we shouldn't take the fields lat en long into account and always use deploy_lat and deploy_long.

hope this helps

**Comment by LienReyserhove** [comment]
Thanks for the help, I will thus use `deploy_lat` and `deploy_long`.

**Comment by LienReyserhove** [comment]
Reopening this issue, as it would be great to at least remove all records for which `latitude` and `longitude` is zero, which is just wrong information. @fwaumans is this an option?

**Comment by fwaumans** [comment]
I don't find any reocrds with `deployment_long =0 or deployment_lat =0`. Which records do you mean?

**Comment by peterdesmet** [comment]
Checking if there is any `deploy_latitude` = 0 and `deploy_longitude` = 0. Indeed, none have those:

- [x] 2010_phd_reubens
- [x] 2010_phd_reubens_sync
- [x] 2011_rivierprik
- [x] 2012_leopoldkanaal
- [x] 2013_albertkanaal
- [x] 2013_albertkanaal_sync
- [x] 2014_demer
- [x] 2015_dijle
- [x] 2015_homarus
- [x] 2015_phd_verhelst_cod
- [x] 2015_phd_verhelst_eel

Closing issue
