### ISSUE TITLE
Clean station names

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#63]
How much "freedom" do we have in cleaning values in `station_name` (`vliz.deployments_view` table)? While inspecting the content of this field (see #60), I found an inconsistent use of capital letters, e.g.:

- Use of small letters vs capital letters for codes: `ak-1` vs `HH1`
- abbreviations **starting** with small letter vs capital letter: `ngOudsa` vs `RingvN`
- use of full location name: `TOEVOERKANAAL` or `Test Rotselaar`

I could suggest some improvements but I need to know whether these values are fixed or not.

**Comment by PieterjanVerhelst** [comment]
In general, a station name exist of two parts: 
1) an acronym of the respective waterway (e.g. s for Schelde, bpns for Belgian part of the North Sea, ak for Albertkanaal...).
2) a location identifier, which can be the name of a naval buoy (mainly in bpns and westerschelde), the name of a city or village, or just a number

Everything can be in lower case letters :-).

**Comment by LienReyserhove** [comment]
Ok, thanks for the input, I will revise all station names and will feed back later!

**Comment by peterdesmet** [comment]
@PieterjanVerhelst Do we still plan to clean `station_name` in deployments?

**Comment by PieterjanVerhelst** [comment]
@peterdesmet I think we should definitely use a standard for station name nomenclature. However, changing the current names may be difficult. Is this necessary? If so, I suggest to create a list of station_names that need to be altered with the project. It is than up to the PI of that particular project to come up with a more standardised station name.

**Comment by peterdesmet** [comment]
> (changing current names) Is this necessary?

No, and I guess we should not attempt this now (for the publication of the data paper), as it will take too much time. Might be good to suggest a format in the definition of that field though, but I'll leave that up to you and other researchers. 😉
