### ISSUE TITLE
Station_name does not equal deployment_station_name in detections table

### ISSUE THREAD

**Issue by LienReyserhove** [inbo/etn-occurrences#64]
`vliz.detections_view` includes two fields for `station_name`: `station_name` and `deployment_station_name`. I would expect that these values of these fields are identical. This is not the case for the following stations though. Could this be corrected in the database?

1. Cases where `station_name` is more or less similar to `deployment_station_name`

station_name | deployment_station_name
--- | ---
A1-Bis | bpns-A1BIS
Belreef 1 | BPNS-Belreef1
BPNS-CPOWERREEFBALLS-CPOD | bpns-Cpowerreefballs-CPOD
bpns-OH6 | bpns-O6
bpns - WK12 | bpns-WK12
CNB07 | bpns-CNB07
Dendermonde | s-Dendermonde
Lier GN | gn-Lier
LIER KN | kn-Lier
LIER SA | bn-Lier
M-1-1 | M-1
M-2-1 | M-2
M-3-1 | M-3
M-4-1 | M-4
M-4A-1 | M-4A
M-5-1 | M-5
M-6-1 | M-6
me-7 | me-7-2
S-1-1 | s-1
S-2-1 | s-2
S-2A-1 | s-2a
S-3 | s-3
S-3-1 | s-3
s-4-1 | s-4
S-4A-1 | s-4a
s-4b-1 | s-4b
s-4c | de-3
s-4c-1 | s-4c
s-5-1 | s-5
s-6-1 | s-6
s-7-1 | s-7
s-8-1 | s-8
s-9-1 | s-9
S9-2 | S09-2
ST010 | S10
ST08 | S08
st09 | S09
ST12 | S12
ST13 | S13
ST14 | S14
ST15 | S15
ST17 | S17
st18 | S18
st18 | ak-29
st7 | S07
Wetteren | s-Wetteren
Wichelen | s-Wichelen
ws-2c | ws-2C
ws-PPb | ws-PPB
ws-pvtss | ws-PVTSS
Zandvlietsluis Albertkanaal B | zandvlietsluis haven B

2. Cases where `station_name` is deviating from `deployment_station_name`

station_name | deployment_station_name
--- | ---
120095 | ma-2
1 PPC | ws-PPC
2 | ak-3
3 | ak-1
4 | ak-5
8 | ak-8
9 | ak-11
BOEREKREEK NATUURRESERVAAT | bh-10
Boudewijnsluis Albertkanaal | ak-44
Boudewijnsluis Schelde | ak-45
bpns-oostduinkerke | bpns-Whitley
Diepenbeek SA | ak-25
Duwvaartsluis Ham | ak-32
Genk SA | ak-23
Genk SO1 b | ak-21
Genk SO na 19 november | ak-22
GROTE GEUL NOTARIS | bh-30
GROTE GEUL UITSTROOM | bh-29
GROTE KIL SO | bh-26
Ham SA | ak-33
Ham Sluis Midden | ak-31
Hasselt SO | ak-26
Haven SA Braakman | bh-37
Houten brug SA gemaal | bh-31
kanaal Dessel-Schoten | ak-43
Kwaadmechelen-Dessel 21-08-15 | ak-34
LEOPOLDKANAAL MONDING BOEREKREEK |  
LEOPOLDKANAAL MONDING BOEREKREEK | bh-9
Leopoldkanaal nood zoekt troost | bh-22
LEOPOLDKANAAL ZONNEBRUG | bh-7
M-6 | de-7
Meuse-amont Monsin et c. Albert (Metro) | ak-9
Olen SA | ak-36
Olen SO | ak-35
Royersluis Albertkanaal | ak-42
Royersluis Schelde | ak-41
sa hasselt (11 mei 2015) | ak-27
SA stuw St Laureins | bh-5
Schelde - Rijnverbinding | ak-48
Sluis RO Ham | ak-30
so diepenbeek (11 mei 2015) | ak-24
STUW SINT LAUREINS SO (vervanging) | bh-6
Toevoerkanaal Isabellagemaal | bh-21
Toevoerkanaal WKC Ham | ak-28
Uitzet SO2 | ak-19
Voorhaven Zeebrugge | s-2
Wijnegem SA | ak-40
Wijnegem SO | ak-39
Zandvlietsluis Schelde | ak-47

**Comment by PieterjanVerhelst** [comment]
I checked the stations for project `Zeeschelde` (with `s-` in station name), `2012_leopoldkanaal` (with `bh-` in station name), and the three `Westerschelde` arrays (with `ws-` in station name). Here are the station names that need to be changed:
* `s-4c` is the station name, and not `de-3`. However, could you check that the deployment date of this station is later than 27/04/2015?
* `LEOPOLDKANAAL MONDING BOEREKREEK` is `bh-9` (missing `deployment_station_name` field in second table)
* `me-7` has `M-7` in column `deployment_station_name`.
* `Voorhaven Zeebrugge` is not `s-2`. I would think it is `bh-2`, but @LienReyserhove could you give me the coordinates of deployment with `Voorhaven Zeebrugge` so I can verify?

@jreubens could you check the station names for the bpns?
@IPauwels could you check the station names for the Albert Canal? Especially the receivers involved in the VPS study in Ham (with `HH` and `st` in the station name)? The others, with `ak-` in the station name are correct.

**Comment by jreubens** [comment]
@fwaumans on which level do we have each of this names?
I guess deploy_station_name is on deployment level and the relevant one...

**Comment by fwaumans** [comment]
I missed this issue. We keep track of station name on 

- detection level: I guess this station name is stored in the receiver
- deployment level: this station name is completed when adding a deployment in the database.

I think the one on deployment level is the most relevant one.
