### ISSUE TITLE
What deployments to include

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#69]
@IPauwels @PieterjanVerhelst @jreubens What receiver deployments should be included for a dataset? For example `2011_rivierprik` has 117,046 detections for 30 (of its 39) animals. Those detections are made by 29 receivers, over 88 deployments. Which deployments should be included in `deployments.csv`?

1. If we limit to the 88 deployments with detections, then we are excluding (potentially useful information on) deployments without detections
2. If we expand to _all_ (263) deployments of the 29 included receivers, then we a) at least include deployments for which there are no detections, b) are still excluding deployments of receivers that didn't have a single detection from this project and c) are potentially covering a much longer time period than may be necessary.

Do you have a better idea of how to define the relevant deployments (from an animal project standpoint)? I.e. to allow the user to understand what receivers where deployed at the time of the animal project?

**Comment by jreubens** [comment]
Hmmm that is indeed a difficult one with our network of receivers.
We have to watch out with the receivers, as a receiver can change place over time...

Some thoughts:
1. we limit to deployments within tag life of the animals at stake (tags die off after certain period, thus limit to this)
2. deployments belong to a specific network. All deployments of that network should be included... e.g if an eel is seen on BPNS we should include all deployments of BPNS active in that period as this gives also info on where the eel hasn't gone... and you can easily filter out the deployments without detections (if we add an extra column with detections yes or no)
3. some expert judgement is needed for each project and thus some manual selection or removal of deployments can be done if needed
@IPauwels ; @PieterjanVerhelst  let me know your thoughts

**Comment by peterdesmet** [comment]
@jreubens I definitely like option 2: see what network projects are included in the detections and get all deployments for that network (with or without using a time frame). That way we include deployments/receivers without detections, and it is easy to implement and communicate in the metadata.

**Comment by peterdesmet** [comment]
https://github.com/inbo/etn-occurrences/pull/70 shows the effect of selecting on network_project_code. I think it is a good implementation, even without selecting on a time frame (as network_projects seem to be defined in time anyway).

**Comment by IPauwels** [comment]
"Do you have a better idea of how to define the relevant deployments (from an animal project standpoint)? I.e. to allow the user to understand what receivers where deployed at the time of the animal project?"

Selecting on network project code seems fine by me. Do I understand it correctly that this is the same as taking the time frame from the first to the last date in the animal project that a (minimally one) tag was transmitting?

**Comment by peterdesmet** [comment]
The time frame is not necessarily the same: it is defined by how long a network project lasts. Basically, what happens now is:

1. animal_project => get associated animal metadata => get associated tag metadata
2. animal_project => get associated detections
3. detections => get associated network_projects: i.e. the networks that picked up those animals
4. network_projects => get all deployments: **this will cover a time window defined by the network_project**. If I understand correctly, some network_projects are closed (no more deployments are associated with those) and others are open ended.
5. deployments across those network projects => get receiver metadata

The above is fine by me. The only downside might be that it can include non-relevant deployments from network projects that continue long after the animal project has finished, but those can be easily ignored by the users, as the deployments have a start and end date.

**Comment by peterdesmet** [comment]
For e.g. `2011_rivierprik`, the detections only cover network project `bovenschelde`, which had its last deployment picked up in 2012-09-03.

**Comment by IPauwels** [comment]
Ok, I understand! Yes, I share your thought on the fact that users can easily ignore irrelevant deployments. If it should be a problem still, then I think that additionally selecting deployments based on the time frame of the animal project (as mentioned by Jan) is a good additional step, and perhaps also a double check by the investigator. I leave this up to your preferences. The suggestions made are fine by me.

**Comment by peterdesmet** [comment]
Thanks, merging #70 and closing this one.
