### ISSUE TITLE
Orphaned deployments

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#71]
In the animal project `2012_leopoldkanaal` I noticed there are detections associated with deployments **that do not have an associated `network_project_code`**:

receiver_id | deployment_fk | network_project_code | from | to | detections
-- | -- | -- | -- | -- | --
VR2W-115438 | 1343 | none | 2015-05-25 02:02:54 | 2015-08-18 22:57:18 | 44

This _orphaned deployment_ is not listed in the `deployments_view`, probably because it does not have an associated `network_project_code`. I can therefore not retrieve any information about it (and include it in the dataset).

@IPauwels @PieterjanVerhelst @jreubens Is this a data quality issue? Should all deployments be associated with a `network_project_code`? If so, can this be corrected? I noticed receiver `VR2W-115438` has deployments associated with `leopold` and `zeeschelde`.

**Comment by PieterjanVerhelst** [comment]
This is strange. I would argue that all deployments are indeed associated with a `network_project_code`, for each deployment is part of a network. According to the date, this deployment is part of the network project in the Leopold canal. I couldn't find a specific network_project_code, is it therefore possible this belongs to `lifewatch`?

**Comment by peterdesmet** [comment]
The `network_project_code` for Leopold canal is `leopold`.

**Comment by peterdesmet** [comment]
Anyone know how to assign this in the ETN application?

**Comment by jreubens** [comment]
If I search on deployment_fk it seems I don't have access to the deployment. Which is strange as well.
What do you mean with assigning in ETN application @peterdesmet 
@PieterjanVerhelst: I can see only two deployments linked to lifewatch, but not covering the dates specified

**Comment by PieterjanVerhelst** [comment]
@jreubens these 2 deployments should be changed to the correct project network. For instance, I know that Jolien added station `ws-STD3` under project network `lifewatch`, while this should be `zeeschelde` (thought she changed it, but in the ETN database it is still under `lifewatch`). That is, lifewatch exists of various project networks and is not a project network in itself, to my opinion.
For the 'orphaned' deployment, as far as I can tell, this is part of network project `leopold`.

**Comment by peterdesmet** [comment]
Ok, from your comments it is quite clear _what_ should be done:

deployment_id | receiver_id | station_name | current nw project | new nw project
--- | --- | --- | --- | ---
5032 | FAKE-TEMP | ws-STD3 | Lifewatch | zeeschelde **done**
4426 | VR2Tx-480063 | ws-STD3 | Lifewatch | zeeschelde **done**
1343 | VR2W-115438 | ? | none | leopold

It is unclear _how_ it can be done. In the ETN application I cannot edit deployments. The last one is not even displayed. @jreubens is this something that should be done at the database side? @fwaumans

**Comment by peterdesmet** [comment]
@IPauwels, the same issue exists for `2014_demer`:

receiver_id | deployment_fk | network_project_code | from | to | detections
--- | --- | --- | --- | --- | ---
VR2W-122362 | 1382 | no_info | 2014-07-11 23:40:48 | 2014-09-05 23:18:04 | 490
VR2W-122367 | 1383 | no_info | 2014-07-11 18:11:00 | 2014-12-16 10:21:53 | 1952
VR2W-124060 | 1384 | no_info | 2014-07-02 00:02:38 | 2014-09-07 02:18:53 | 227

**Comment by fwaumans** [comment]
In the `project` table in the database, two network projects does not have a real name:
**id**|**name**|**projectcode**|**type**|**startdate**|**enddate**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
609|NONE|none|network||
608||no\_info|network||

**Comment by peterdesmet** [comment]
And deployments associated with these are excluded from the deployment view? Can this be _included_ in the deployment view?

**Comment by fwaumans** [comment]
Wait, I'm running a query.

**Comment by IPauwels** [comment]
If you give me the list of deployments that miss the projectcode, then I will provide it so that it can be adapted.
As Pieterjan indicated, the one deployed in the Leopold canal can have projectcode 'Leopold'.

How/where did you see that the others are from 2014_demer?

**Comment by fwaumans** [comment]
I think this are deployments we imported from an excel file from INBO when we started with the ETN database. We did not have a project for these deployments. They don't occur in the deployments view because no access rights were granted to these projects.
[project_none_no_info.xlsx](https://github.com/inbo/etn-occurrences/files/5187174/project_none_no_info.xlsx)

**Comment by fwaumans** [comment]
You have now access to the projects 'NONE' and 'NO_INFO'.

**Comment by peterdesmet** [comment]
@fwaumans thanks for updating the 2 zeeschelde deployments already and make `no_info` and `none` available in the deployments.

@IPauwels @PieterjanVerhelst let's try to assign the **network** and **station** to the remaining ones:

pk | receiver_id | network_project_code | station_name | deploy_date_time | recover_date_time | between deployments of
-- | -- | -- | -- | -- | -- | --
1335 | VR2W-112292 | none → remove deployment (no assoc detections) |   | NA | 2015-11-18 | leopold (bh-5), zeeschelde (s-Dendermonde)
1343 | VR2W-115438 | none → leopold |   | NA | 2015-11-18 | leopold (bh-9), zeeschelde (s-Wichelen)
1345 | VR2W-115444 | none → remove deployment (no assoc detections) |   | NA | 2015-11-18 | leopold (bh-8), zeeschelde (s-Vlassenbroek)
1382 | VR2W-122362 | no_info → demer | de-22 | 2014-07-11 00:00:00 | 2014-09-05 00:00:00 | dijle (M-3)
1383 | VR2W-122367 | no_info → demer | de-15 | 2014-07-11 00:00:00 | 2014-12-16 00:00:00 | demer (de-15), zeeschelde (s-4b)
1384 | VR2W-124060 | no_info → demer | de-21 | 2014-07-02 00:00:00 | 2014-09-07 00:00:00 | demer (de-21)

**Comment by PieterjanVerhelst** [comment]
@peterdesmet is it possible to see some detections of `VR2W-112292` and `VR2W-115444`? I would think both are part from the network `leopold`, but it is strange that there is only 1 day difference between the recover data of these orphaned deployments and the non-orphaned deployment in the databse.

**Comment by peterdesmet** [comment]
Will send them by email. @IPauwels I think the demer once are more straightforward (they all have stations associated with Demer)

**Comment by PieterjanVerhelst** [comment]
Quite odd, these deployments have detections belonging to different projects (station name between brackets):
+ `115444`: detections for `bovenschelde` (`SOmZwa`), `leopold` (`bh-8`), and `zeeschelde` (`s-Vlassenbroek`)
+ `112292`: detections for `leopold` (`bh-5`), and `zeeschelde` (`s-Dendermonde`)

Is there a possibility to check if these detections are already in the database and therefore these orphaned deployments could be doubles? Really not a clue how this could have happened...

**Comment by IPauwels** [comment]
I am afraid that the same might have happened to the "Demer-receivers/orphaned deployments". I will need to have the detections of those as well to be sure. Is it possible to send me these by email, Peter? Many thanks!!

**Comment by peterdesmet** [comment]
@IPauwels any progress on this issue? It is blocking the upload for some datasets.

**Comment by IPauwels** [comment]
Sorry, checking it!

**Comment by IPauwels** [comment]
Yes, this is all demer! 

My apologies, I had misunderstood a bit the problem and thought it was more work to check it.. 
Truly sorry!

**Comment by peterdesmet** [comment]
Thanks @IPauwels!

@PieterjanVerhelst can we assign 1335 and 1345 (see https://github.com/inbo/etn-occurrences/issues/71#issuecomment-689486825) to `leopold` now, even though it is somewhat odd?

**Comment by PieterjanVerhelst** [comment]
@peterdesmet it depends:

- 1335 (receiver VR2W-112292): 
   * until 30/06/2012: project `bovenschelde`
   * 2012-07-01 till 2015-11-17: project `leopoldkanaal`

- 1345 (receiver VR2W-115444): 
   * until 30/06/2012: project `bovenschelde`
   * 2012-07-01 till 2015-11-17: project `leopoldkanaal`

However, according to the ETN database, all deployments are there so I think the detections are already in the database. So where do these 2 files come from?

**Comment by peterdesmet** [comment]
Hi @fwaumans, I have summarized all the discussions. Here are the actions to take in database:

pk | receiver_id | network_project_code | remarks | deployment table | detection table
-- | -- | -- | -- | -- | --
1335 | VR2W-112292 | none | no deploy date, recover date (2015-11-18) 1 day after previous deployment (2792), no associated detections | remove record | no action
1343 | VR2W-115438 | none | no deploy data, recover data (2015-11-18) 2 days after previous deployment (2807), 44 associated detections fall all within range of that previous deployment | remove record | associate 44 detections with 2807 (not 1343)
1345 | VR2W-115444 | none |  no deploy date, recover date (2015-11-18) 1 day after previous deployment (1422), no associated detections | remove record | no action
1382 | VR2W-122362 | no_info | deployment (2014-07-11 to 2014-09-05) falls completely within 2933 (2014-07-01 to 2015-02-13). Associated records (2014-07-12 to 2014-09-06) do too | remove record | associate 440 detections with 2933 (not 1382)
1383 | VR2W-122367 | no_info | deployment (2014-07-11 to 2014-12-16) does not overlap with other deployments, associated detections fall within range | assign network project code `demer` | no action
1384 | VR2W-124060 | no_info | deployment (2014-07-02 to 2014-09-07) does not overlap with other deployments, associated detections fall within range | assign network project code `demer` | no action

**Comment by fwaumans** [comment]
All actions were taken in the database.
