### ISSUE TITLE
Assign cods to 2015_phd_verhelst

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#73]
These animals are still listed under `2015_phd_verhelst_eel`, while they should go under `2015_phd_verhelst_cod`

animal_id | tag_id
--- | ---
270 | A69-1601-14869 
628 | A69-1601-58577
271 | A69-1601-14869 
2821 | A69-1601-58577
2827 | A69-9006-904,A69-9006-903

**Comment by PieterjanVerhelst** [comment]
Indeed, we are looking into it. I couldn't change the project name for those animals (probably a bug).
