### ISSUE TITLE
2015_phd_verhelst_cod: 3 unknown receivers

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#74]
The detection data of `2015_phd_verhelst_cod` contains 222,410 detections of **3 unknown receivers** linked to `bpns` that cannot be found in deployments or receivers:

```
VR2C69-450114
VR2C69-450136
VR2C69-450113
```

@PieterjanVerhelst can these be added to the database (otherwise I'm getting a lot of foreign key errors)?

**Comment by jreubens** [comment]
I don't understand the issue. If you get detections, you should have deployments. All three receivers have deployments in bpns. I don't think there are missing deployments here. @peterdesmet What exactly do you want us to do?

**Comment by peterdesmet** [comment]
@jreubens I just checked again, and those 3 receivers are not available in the `deployments` and `receivers` view. They do seem to be available under the names:

VR2C69-450114 → VR2C-450114
VR2C69-450136 → VR2C69-450136
VR2C69-450113 → VR2C-450113

But that is not how they are written in the detections. I am not sure how that can happen, but could these be updated in the detections view?

**Comment by peterdesmet** [comment]
@jreubens @fwaumans can this issue be resolved? It is blocking the data publication.

**Comment by fwaumans** [comment]
The receiver name is completed in two places in the database:
1. in the detectiontable, the receivername comes from the device itself via the detectionfile (this one is shown in the view)
2. in the deployment, completed by the user.

In some rare occasions, they don't correspond. I have replaced the mentioned receivernames in the detectiontable.

**Comment by peterdesmet** [comment]
Great! Works now.
