### ISSUE TITLE
Duplicate animal in 2015_phd_verhelst_cod

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#75]
In `2015_phd_verhelst_cod` there are two animals which are the cause of duplicate detections (#72). They have the same tag, but no `recapture_date_time` and very similar information. @PieterjanVerhelst can you verify these are indeed different animals or if these are duplicates that should be merged?

All fields that are not NA:

field | animal 628 | animal 2821
--- | --- | ---
pk | 628 | 2821
animal_id | 628 | 2821
animal_project_code | 2015_phd_verhelst_cod | 2015_phd_verhelst_cod
tag_id | A69-1601-58577 | A69-1601-58577
tag_fk | 502 | 502
scientific_name | Gadus morhua | Gadus morhua
common_name | Atlantic cod | Atlantic cod
animal_label | A66 | 
capture_date_time | 2015-07-31T02:00:00+0200 | 2018-01-12T13:00:00+0100
capture_location | Reefballs C-Power | C-Power reefballs
capture_latitude | 51.5800044 | 51.5800044
capture_longitude | 2.9954894 | 2.9954894
capture_method | line fishing | line fishing
capture_depth |  | 26m
release_date_time | 2015-07-31T02:00:00+0200 | 2018-01-12T14:00:00+0100
release_location | Reefballs C-Power | C-Power reefballs
release_latitude | 51.5800044 | 51.5800044
release_longitude | 2?9954894 | 2.9954894
length1_type | total length | total length
length1 | 39 | 44
length1_unit | cm | cm
sex | unknown | unknown
wild_or_hatchery | wild | wild
surgery_date_time | 2015-07-31T02:00:00+0200 | 
surgery_location | Reefballs C-Power | 
surgery_latitude | 515800044 | 
surgery_longitude | 29954894 | 
treatment_type | INTERNAL TAGGING | 
sedative |  | 2-Phenoxyethanol
comments |  | DJ 44

**Comment by PieterjanVerhelst** [comment]
@peterdesmet  these are indeed different fish. The fish that was tagged first was caught on 10-08-2015 11.30h (GMT) at N 51.30.430   O 002.57.017. If I add this information to the ETN database, the issue will be solved. Is that correct?

**Comment by PieterjanVerhelst** [comment]
Update: when I filled in the recapture date in the ETN database I got an error that I could not edit the animal due to the expired tag end date. However, it should always be possible to fill in the recapture date of an animal since it can be caught after the tag expired. @jreubens can you look at this?

**Comment by jreubens** [comment]
I'm checking with Aubri, will update you as soon as I have an answer...

**Comment by jreubens** [comment]
@PieterjanVerhelst solved, this issue was a result of having 2 animals with the same ID but not having a recapture date, than the system gets confused.
But it is updated now...

**Comment by peterdesmet** [comment]
Great! No more duplicate detections. Still an issue with unknown receiver_ids: see #74.
