### ISSUE TITLE
Duplicate animal in 2013_albertkanaal

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#76]
In `2013_albertkanaal` there are two animals which are the cause of duplicate detections (#72). They have the same tag, but no `recapture_date_time` and very similar information. @PieterjanVerhelst can you verify these are indeed different animals or if these are duplicates that should be merged? To me it seems more clearcut than #75 that these are indeed duplicates?

All fields that are not NA:

field | animal 524 | animal 525
--- | --- | ---
pk | 524 | 525
animal_id | 524 | 525
animal_project_code | 2013_albertkanaal | 2013_albertkanaal
tag_id | A69-1601-34486 | A69-1601-34486
tag_fk | 618 | 618
scientific_name | Salmo salar | Salmo salar
common_name | Atlantic salmon | Atlantic salmon
capture_date_time | 2015-04-22T02:00:00+0200 | 2015-04-22T02:00:00+0200
capture_location | hatchery Erezée | hatchery Erezée
release_date_time | 2015-04-22T02:00:00+0200 | 2015-04-22T02:00:00+0200
release_location | Grosses Battes | Grosses Battes
release_latitude | 50.614681 | 50.614681
release_longitude | 5.604782 | 5.604782
length1_type | total length | total length
length1 | 28.4 | 29.6
length1_unit | cm | cm
weight | 254 | 329.8
weight_unit | g | g
sex | unknown | unknown
wild_or_hatchery | hatchery | hatchery
treatment_type | INTERNAL TAGGING | INTERNAL TAGGING

**Comment by peterdesmet** [comment]
Ping @IPauwels

**Comment by PieterjanVerhelst** [comment]
@peterdesmet , no idea about these salmons since I was not involved in the salmon tagging. I know some salmons died after surgery, so probably the first had died after which the transmitter was removed to put it in the second salmon. But I let @IPauwels give feedback on this one.

**Comment by IPauwels** [comment]
@peterdesmet  animal 524 was dead after tagging and the tag was then used for tagging animal 525. So, animal 524 can be removed from the dataset.

**Comment by PieterjanVerhelst** [comment]
@IPauwels I would suggest to remove the animal from the ETN database as well, since it was not released back in the wild.

**Comment by peterdesmet** [comment]
Yes, can someone remove animal 524 from the database. That is the source for everything.

**Comment by peterdesmet** [comment]
Seems I had the rights to remove it myself, so I have done so.

**Comment by IPauwels** [comment]
Ok, thanks!

**Comment by peterdesmet** [comment]
Great, no more duplicate detections, dataset is now valid:

```
[valid] animals.csv
[valid] tags.csv
[valid] detections.csv
[valid] deployments.csv
[valid] receivers.csv
```

**Comment by jreubens** [comment]
you can indeed manage your own animals in ETN.... :-)

**Comment by peterdesmet** [comment]
😄 Cool, just didn't know they were my salmons.
