### ISSUE TITLE
Remove Sentinel tags from 2010_phd_reubens

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#79]
Although sentinel tags have been move to a separate project, they still seem to be included in `2010_phd_reubens` as well:

<img width="979" alt="Screenshot 2020-11-13 at 15 31 18" src="https://user-images.githubusercontent.com/600993/99083157-6ba9b080-25c5-11eb-9cc7-700a6814ece9.png">

**Comment by jreubens** [comment]
this is solved now.

**Comment by peterdesmet** [comment]
One record is still under both `A69-1303-65309`

**Comment by peterdesmet** [comment]
Is solved now
