### ISSUE TITLE
Should treatment_type = INTERNAL TAGGING not be tagging_type = internal?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/etn-occurrences#80]
I notice that most animal records have `treatment_type` = `INTERNAL TAGGING`. This seems an odd field for that. Should this not be `tagging_type` = `internal`? @PieterjanVerhelst @jreubens @IPauwels

**Comment by PieterjanVerhelst** [comment]
@peterdesmet indeed, that information belongs to `tagging_type`. `Treatment_type` is to assign an animal to a specific study group, for instance the 'control group'.

**Comment by peterdesmet** [comment]
👍  How should sentinel/sync tags be marked?

**Comment by peterdesmet** [comment]
@IPauwels I notice `Platichthys flesus` (in `2015_dijle`) has tagging type `external`. One however has `internal`. Does this seem correct or should all have `external`?

**Comment by PieterjanVerhelst** [comment]
@peterdesmet imo `tagging_type` is redundant for sentinel/sync tags. `treatment_type` is debatable, but can also be left open. @jreubens and @IPauwels  what do you think?

**Comment by peterdesmet** [comment]
@ipauwels suggests for the `2012_leopoldkanaal` sync tags to add `treatment_type: receiver clock synchronisation`

**Comment by peterdesmet** [comment]
@jreubens what `treatment_type` would you want for the sentinel tags in `2010_phd_reubens_sync`?

**Comment by IPauwels** [comment]
When fine scale positioning data are added to the database (2 and 3D tracking) also reference, test and sentinel tags will be added, so we could check (perhaps in another issue?) how to define these. Treatment type seems the appropriate field to indicate something about this. A suggestion for values of treatment type: 

- sync tag: a tag which is used for "_receiver clock synchronisation_" (or shorter: "_synchronisation_")

- reference tag: "_calibrating positioning accuracy_" (or shorter: "_positioning accuracy_")

- sentinel tag: "_receiver performance estimation_" or _"detection range estimation"_ ??I do not have too much experience with sentinel tags in fact??
- test tag: "_system accuracy estimation_" or "_system validation_" or .... ?

**Comment by peterdesmet** [comment]
Thanks Ine, for now I mostly need a `treatment_type` for sentinel tag.

**Comment by jreubens** [comment]
I guess we can delete sentinel tags from the system and only use sync tags... both names are mixed...
treatment_type and tagging_type seem redundant to for sync tags (as @PieterjanVerhelst ) mentioned
a sync tag is always for clock syncronisation... this is not a treatment.... A treatment is for an experiment.
THus I would not add this info for sync, sentinel, built-in or range
only for animal tags

**Comment by peterdesmet** [comment]
Indeed, no need to use `treatment_type` (as that is something completely different). `tagging_type` can be left empty too. Should we just rely on the `scientific_name` then, and rename `Sentinel` to `Sync tag` (cf. Albertkanaal)?

**Comment by jreubens** [comment]
Yes indeed. I'll change sentinel to sync

**Comment by peterdesmet** [comment]
:+1: I have also removed `treatment_type=SENTINEL_TAG`. For two records it seems the scientific name will have to be changed by Aubri

**Comment by peterdesmet** [comment]
By removing a duplicate animal, I was able to update all scientific names.
